[pytest]
# Look for tests under src/tests
testpaths = src/tests
python_files = test_*.py *_test.py
addopts = -ra

# Turn warnings into errors in tests (comment out if too strict)
filterwarnings =
    error

log_cli = true
log_cli_level = INFO
