"""
This type stub file was generated by pyright.
"""

class EnsembleCateEstimator:
    """
    A CATE estimator that represents a weighted ensemble of many CATE estimators.

    Returns their weighted effect prediction.

    Parameters
    ----------
    cate_models : list of BaseCateEstimator objects
        A list of fitted cate estimator objects that will be used in the ensemble.
        The models are passed by reference, and not copied internally, because we
        need the fitted objects, so any change to the passed models will affect
        the internal predictions (e.g. if the input models are refitted).
    weights : np.ndarray of shape (len(cate_models),)
        The weight placed on each model. Weights must be non-positive. The
        ensemble will predict effects based on the weighted average predictions
        of the cate_models estiamtors, weighted by the corresponding weight in `weights`.
    """
    def __init__(self, *, cate_models, weights) -> None:
        ...
    
    def effect(self, X=..., *, T0=..., T1=...): # -> Incomplete:
        ...
    
    def marginal_effect(self, T, X=...): # -> Incomplete:
        ...
    
    def const_marginal_effect(self, X=...): # -> Incomplete:
        ...
    
    @property
    def cate_models(self): # -> list[Any]:
        ...
    
    @cate_models.setter
    def cate_models(self, value): # -> None:
        ...
    
    @property
    def weights(self): # -> Any:
        ...
    
    @weights.setter
    def weights(self, value): # -> None:
        ...
    


