"""
This type stub file was generated by pyright.
"""

from sklearn.base import BaseEstimator
from ..utilities import deprecated

DTYPE = ...
DOUBLE = ...
SPLITTERS = ...
class BaseTree(BaseEstimator):
    def __init__(self, *, criterion, splitter=..., max_depth=..., min_samples_split=..., min_samples_leaf=..., min_weight_fraction_leaf=..., min_var_leaf=..., min_var_leaf_on_val=..., max_features=..., random_state=..., min_impurity_decrease=..., min_balancedness_tol=..., honest=...) -> None:
        ...
    
    def get_depth(self):
        """
        Return the depth of the decision tree.

        The depth of a tree is the maximum distance between the root
        and any leaf.

        Returns
        -------
        self.tree_.max_depth : int
            The maximum depth of the tree.
        """
        ...
    
    def get_n_leaves(self):
        """Return the number of leaves of the decision tree.

        Returns
        -------
        self.tree_.n_leaves : int
            Number of leaves.
        """
        ...
    
    def fit(self, X, y, n_y, n_outputs, n_relevant_outputs, sample_weight=..., check_input=...):
        """
        Fit the tree to data.

        Child class needs to have initialized the property `random_state_` before
        calling this super `fit`.
        """
        ...
    
    def get_train_test_split_inds(self): # -> tuple[ndarray[_AnyShape, dtype[signedinteger[_NBitIntP]]], ndarray[_AnyShape, dtype[signedinteger[_NBitIntP]]]] | tuple[_Array1D[signedinteger[_NBitIntP]], _Array1D[signedinteger[_NBitIntP]]]:
        """
        Regenerate the train_test_split of input sample indices.

        Produces the split that was used for the training and the evaluation split of the honest tree construction
        structure.

        Uses the same random seed that was used at ``fit`` time and re-generates the indices.
        """
        ...
    
    def apply(self, X, check_input=...):
        """Return the index of the leaf that each sample is predicted as.

        Parameters
        ----------
        X : {array_like} of shape (n_samples, n_features)
            The input samples. Internally, it will be converted to
            ``dtype=np.float64``
        check_input : bool, default True
            Allow to bypass several input checking.
            Don't use this parameter unless you know what you do.

        Returns
        -------
        X_leaves : array_like of shape (n_samples,)
            For each datapoint x in X, return the index of the leaf x
            ends up in. Leaves are numbered within
            ``[0; self.tree_.node_count)``, possibly with gaps in the
            numbering.
        """
        ...
    
    def decision_path(self, X, check_input=...):
        """Return the decision path in the tree.

        Parameters
        ----------
        X : {array_like} of shape (n_samples, n_features)
            The input samples. Internally, it will be converted to
            ``dtype=np.float64``
        check_input : bool, default True
            Allow to bypass several input checking.
            Don't use this parameter unless you know what you do.

        Returns
        -------
        indicator : sparse matrix of shape (n_samples, n_nodes)
            Return a node indicator CSR matrix where non zero elements
            indicates that the samples goes through the nodes.
        """
        ...
    
    @property
    @deprecated(message="This attribute is deprecated and will be removed in a future version; " "please use the 'n_features_in_' attribute instead.")
    def n_features_(self):
        ...
    


