"""
This type stub file was generated by pyright.
"""

from ._ensemble import BaseEnsemble, _partition_estimators
from ._utilities import _accumulate_oob_preds, _accumulate_prediction, _accumulate_prediction_and_var, _accumulate_prediction_var, _get_n_samples_subsample

__all__ = ["BaseEnsemble", "_partition_estimators", "_get_n_samples_subsample", "_accumulate_prediction", "_accumulate_prediction_var", "_accumulate_prediction_and_var", "_accumulate_oob_preds"]
