"""
This type stub file was generated by pyright.
"""

import sklearn
from abc import ABCMeta, abstractmethod
from sklearn.base import BaseEstimator
from packaging.version import parse

if parse(sklearn.__version__) < parse("1.5"):
    ...
else:
    ...
class BaseEnsemble(BaseEstimator, metaclass=ABCMeta):
    """
    Base class for all ensemble classes.

    Warning: This class should not be used directly. Use derived classes
    instead.

    Parameters
    ----------
    base_estimator : object
        The base estimator from which the ensemble is built.
    n_estimators : int, default 10
        The number of estimators in the ensemble.
    estimator_params : list of str, default tuple()
        The list of attributes to use as parameters when instantiating a
        new base estimator. If none are given, default parameters are used.

    Attributes
    ----------
    base_estimator_ : estimator
        The base estimator from which the ensemble is grown.
    estimators_ : list of estimator
        The collection of fitted base estimators.
    """
    @abstractmethod
    def __init__(self, base_estimator, *, n_estimators=..., estimator_params=...) -> None:
        ...
    
    def __len__(self): # -> int:
        """Return the number of estimators in the ensemble."""
        ...
    
    def __getitem__(self, index):
        """Return the index'th estimator in the ensemble."""
        ...
    
    def __iter__(self):
        """Return iterator over estimators in the ensemble."""
        ...
    


