"""
This type stub file was generated by pyright.
"""

from .dml import _BaseDML
from ..inference._inference import Inference

class _CausalForestFinalWrapper:
    def __init__(self, model_final, featurizer, discrete_treatment, drate) -> None:
        ...
    
    def fit(self, X, T, T_res, Y_res, sample_weight=..., freq_weight=..., sample_var=..., groups=...): # -> Self:
        ...
    
    def predict(self, X): # -> Any:
        ...
    
    @property
    def ate_(self):
        ...
    
    @ate_.setter
    def ate_(self, value): # -> None:
        ...
    
    @property
    def ate_stderr_(self):
        ...
    
    @ate_stderr_.setter
    def ate_stderr_(self, value): # -> None:
        ...
    
    @property
    def att_(self):
        ...
    
    @att_.setter
    def att_(self, value): # -> None:
        ...
    
    @property
    def att_stderr_(self):
        ...
    
    @att_stderr_.setter
    def att_stderr_(self, value): # -> None:
        ...
    


class _GenericSingleOutcomeModelFinalWithCovInference(Inference):
    def prefit(self, estimator, *args, **kwargs): # -> None:
        ...
    
    def fit(self, estimator, *args, **kwargs): # -> None:
        ...
    
    def const_marginal_effect_interval(self, X, *, alpha=...): # -> tuple[generic[Any] | NDArray[bytes_] | NDArray[complex128] | NDArray[str_] | NDArray[Any] | Any | complex | str | bytes | memoryview[int], generic[Any] | NDArray[bytes_] | NDArray[complex128] | NDArray[str_] | NDArray[Any] | Any | complex | str | bytes | memoryview[int]]:
        ...
    
    def const_marginal_effect_inference(self, X): # -> NormalInferenceResults:
        ...
    
    def effect_interval(self, X, *, T0, T1, alpha=...): # -> tuple[generic[Any] | NDArray[bytes_] | NDArray[complex128] | NDArray[str_] | NDArray[Any] | Any | complex | str | bytes | memoryview[int], generic[Any] | NDArray[bytes_] | NDArray[complex128] | NDArray[str_] | NDArray[Any] | Any | complex | str | bytes | memoryview[int]]:
        ...
    
    def effect_inference(self, X, *, T0, T1): # -> NormalInferenceResults:
        ...
    
    def marginal_effect_interval(self, T, X, alpha=...): # -> tuple[generic[Any] | NDArray[bytes_] | NDArray[complex128] | NDArray[str_] | NDArray[Any] | Any | complex | str | bytes | memoryview[int], generic[Any] | NDArray[bytes_] | NDArray[complex128] | NDArray[str_] | NDArray[Any] | Any | complex | str | bytes | memoryview[int]]:
        ...
    
    def marginal_effect_inference(self, T, X): # -> NormalInferenceResults:
        ...
    


class CausalForestDML(_BaseDML):
    """
    A Causal Forest [cfdml1]_ combined with DML-based residualization of the treatment and outcome variables.

    It fits a forest that solves the local moment equation problem:

    .. code-block::

        E[ (Y - E[Y|X, W] - <theta(x), T - E[T|X, W]> - beta(x)) (T;1) | X=x] = 0

    where E[Y|X, W] and E[T|X, W] are fitted in a first stage in a cross-fitting manner.

    Parameters
    ----------
    model_y: estimator, default ``'auto'``
        Determines how to fit the outcome to the features.

        - If ``'auto'``, the model will be the best-fitting of a set of linear and forest models

        - Otherwise, see :ref:`model_selection` for the range of supported options;
          if a single model is specified it should be a classifier if `discrete_outcome` is True
          and a regressor otherwise

    model_t: estimator, default ``'auto'``
        Determines how to fit the treatment to the features.

        - If ``'auto'``, the model will be the best-fitting of a set of linear and forest models

        - Otherwise, see :ref:`model_selection` for the range of supported options;
          if a single model is specified it should be a classifier if `discrete_treatment` is True
          and a regressor otherwise

    featurizer : :term:`transformer`, optional
        Must support fit_transform and transform. Used to create composite features in the final CATE regression.
        It is ignored if X is None. The final CATE will be trained on the outcome of featurizer.fit_transform(X).
        If featurizer=None, then CATE is trained on X.

    treatment_featurizer : :term:`transformer`, optional
        Must support fit_transform and transform. Used to create composite treatment in the final CATE regression.
        The final CATE will be trained on the outcome of featurizer.fit_transform(T).
        If featurizer=None, then CATE is trained on T.

    discrete_outcome: bool, default ``False``
        Whether the outcome should be treated as binary

    discrete_treatment: bool, default ``False``
        Whether the treatment values should be treated as categorical, rather than continuous, quantities

    categories: 'auto' or list, default 'auto'
        The categories to use when encoding discrete treatments (or 'auto' to use the unique sorted values).
        The first category will be treated as the control treatment.

    cv: int, cross-validation generator or an iterable, default 2
        Determines the cross-validation splitting strategy.
        Possible inputs for cv are:

        - None, to use the default 3-fold cross-validation,
        - integer, to specify the number of folds.
        - :term:`CV splitter`
        - An iterable yielding (train, test) splits as arrays of indices.

        For integer/None inputs, if the treatment is discrete
        :class:`~sklearn.model_selection.StratifiedKFold` is used, else,
        :class:`~sklearn.model_selection.KFold` is used
        (with a random shuffle in either case).

        Unless an iterable is used, we call `split(X,T)` to generate the splits.

    mc_iters: int, optional
        The number of times to rerun the first stage models to reduce the variance of the nuisances.

    mc_agg: {'mean', 'median'}, default 'mean'
        How to aggregate the nuisance value for each sample across the `mc_iters` monte carlo iterations of
        cross-fitting.

    drate : bool, default True
        Whether to calculate doubly robust average treatment effect estimate on training data at fit time.
        This happens only if `discrete_treatment=True`. Doubly robust ATE estimation on the training data
        is not available for continuous treatments.

    n_estimators : int, default 100
        Number of trees

    criterion : {``"mse"``, ``"het"``}, default "mse"
        The function to measure the quality of a split. Supported criteria
        are ``"mse"`` for the mean squared error in a linear moment estimation tree and ``"het"`` for
        heterogeneity score.

        - The ``"mse"`` criterion finds splits that minimize the score

          .. code-block::

            sum_{child} E[(Y - <theta(child), T> - beta(child))^2 | X=child] weight(child)

          Internally, for the case of more than two treatments or for the case of two treatments with
          ``fit_intercept=True`` then this criterion is approximated by computationally simpler variants for
          computational purposes. In particular, it is replaced by:

          .. code-block::

            sum_{child} weight(child) * rho(child).T @ E[(T;1) @ (T;1).T | X in child] @ rho(child)

          where:

          .. code-block::

                rho(child) := E[(T;1) @ (T;1).T | X in parent]^{-1}
                                * E[(Y - <theta(x), T> - beta(x)) (T;1) | X in child]

          This can be thought as a heterogeneity inducing score, but putting more weight on scores
          with a large minimum eigenvalue of the child jacobian ``E[(T;1) @ (T;1).T | X in child]``,
          which leads to smaller variance of the estimate and stronger identification of the parameters.

        - The "het" criterion finds splits that maximize the pure parameter heterogeneity score

          .. code-block::

            sum_{child} weight(child) * rho(child)[:n_T].T @ rho(child)[:n_T]

          This can be thought as an approximation to the ideal heterogeneity score:

          .. code-block::

            weight(left) * weight(right) || theta(left) - theta(right)||_2^2 / weight(parent)^2

          as outlined in [cfdml1]_

    max_depth : int, default None
        The maximum depth of the tree. If None, then nodes are expanded until
        all leaves are pure or until all leaves contain less than
        min_samples_split samples.

    min_samples_split : int or float, default 10
        The minimum number of samples required to split an internal node:

        - If int, then consider `min_samples_split` as the minimum number.
        - If float, then `min_samples_split` is a fraction and `ceil(min_samples_split * n_samples)` are the minimum
          number of samples for each split.

    min_samples_leaf : int or float, default 5
        The minimum number of samples required to be at a leaf node.
        A split point at any depth will only be considered if it leaves at
        least ``min_samples_leaf`` training samples in each of the left and
        right branches.  This may have the effect of smoothing the model,
        especially in regression.

        - If int, then consider `min_samples_leaf` as the minimum number.
        - If float, then `min_samples_leaf` is a fraction and `ceil(min_samples_leaf * n_samples)` are the minimum
          number of samples for each node.

    min_weight_fraction_leaf : float, default 0.0
        The minimum weighted fraction of the sum total of weights (of all
        the input samples) required to be at a leaf node. Samples have
        equal weight when sample_weight is not provided.

    min_var_fraction_leaf : None or float in (0, 1], default None
        A constraint on some proxy of the variation of the treatment vector that should be contained within each
        leaf as a percentage of the total variance of the treatment vector on the whole sample. This avoids
        performing splits where either the variance of the treatment is small and hence the local parameter
        is not well identified and has high variance. The proxy of variance is different for different criterion,
        primarily for computational efficiency reasons. If ``criterion='het'``, then this constraint translates to::

            for all i in {1, ..., T.shape[1]}:
                Var(T[i] | X in leaf) > `min_var_fraction_leaf` * Var(T[i])

        If ``criterion='mse'``, because the criterion stores more information about the leaf for
        every candidate split, then this constraint imposes further constraints on the pairwise correlations
        of different coordinates of each treatment, i.e.::

            for all i neq j:
                sqrt( Var(T[i]|X in leaf) * Var(T[j]|X in leaf)
                    * ( 1 - rho(T[i], T[j]| in leaf)^2 ) )
                    > `min_var_fraction_leaf` sqrt( Var(T[i]) * Var(T[j]) * (1 - rho(T[i], T[j])^2 ) )

        where rho(X, Y) is the Pearson correlation coefficient of two random variables X, Y. Thus this
        constraint also enforces that no two pairs of treatments be very co-linear within a leaf. This
        extra constraint primarily has bite in the case of more than two input treatments and also avoids
        leafs where the parameter estimate has large variance due to local co-linearities of the treatments.

    min_var_leaf_on_val : bool, default False
        Whether the `min_var_fraction_leaf` constraint should also be enforced to hold on the validation set of the
        honest split too. If ``min_var_leaf=None`` then this flag does nothing. Setting this to True should
        be done with caution, as this partially violates the honesty structure, since the treatment variable
        of the validation set is used to inform the split structure of the tree. However, this is a benign
        dependence as it only uses local correlation structure of the treatment T to decide whether
        a split is feasible.

    max_features : int, float, {"auto", "sqrt", "log2"}, or None, default None
        The number of features to consider when looking for the best split:

        - If int, then consider `max_features` features at each split.
        - If float, then `max_features` is a fraction and `int(max_features * n_features)` features
          are considered at each split.
        - If "auto", then `max_features=n_features`.
        - If "sqrt", then `max_features=sqrt(n_features)`.
        - If "log2", then `max_features=log2(n_features)`.
        - If None, then `max_features=n_features`.

        Note: the search for a split does not stop until at least one
        valid partition of the node samples is found, even if it requires to
        effectively inspect more than ``max_features`` features.

    min_impurity_decrease : float, default 0.0
        A node will be split if this split induces a decrease of the impurity
        greater than or equal to this value.
        The weighted impurity decrease equation is the following::

            N_t / N * (impurity - N_t_R / N_t * right_impurity
                                - N_t_L / N_t * left_impurity)

        where ``N`` is the total number of samples, ``N_t`` is the number of
        samples at the current node, ``N_t_L`` is the number of samples in the
        left child, and ``N_t_R`` is the number of samples in the right child.
        ``N``, ``N_t``, ``N_t_R`` and ``N_t_L`` all refer to the weighted sum,
        if ``sample_weight`` is passed.

    max_samples : int or float in (0, 1], default .45,
        The number of samples to use for each subsample that is used to train each tree:

        - If int, then train each tree on `max_samples` samples, sampled without replacement from all the samples
        - If float, then train each tree on `ceil(`max_samples` * `n_samples`)`, sampled without replacement
          from all the samples.

        If ``inference=True``, then `max_samples` must either be an integer smaller than `n_samples//2` or a float
        less than or equal to .5.

    min_balancedness_tol: float in [0, .5], default .45
        How imbalanced a split we can tolerate. This enforces that each split leaves at least
        (.5 - min_balancedness_tol) fraction of samples on each side of the split; or fraction
        of the total weight of samples, when sample_weight is not None. Default value, ensures
        that at least 5% of the parent node weight falls in each side of the split. Set it to 0.0 for no
        balancedness and to .5 for perfectly balanced splits. For the formal inference theory
        to be valid, this has to be any positive constant bounded away from zero.

    honest : bool, default True
        Whether each tree should be trained in an honest manner, i.e. the training set is split into two equal
        sized subsets, the train and the val set. All samples in train are used to create the split structure
        and all samples in val are used to calculate the value of each node in the tree.

    inference : bool, default True
        Whether inference (i.e. confidence interval construction and uncertainty quantification of the estimates)
        should be enabled. If ``inference=True``, then the estimator uses a bootstrap-of-little-bags approach
        to calculate the covariance of the parameter vector, with am objective Bayesian debiasing correction
        to ensure that variance quantities are positive.

    fit_intercept : bool, default True
        Whether we should fit an intercept nuisance parameter beta(x).

    subforest_size : int, default 4,
        The number of trees in each sub-forest that is used in the bootstrap-of-little-bags calculation.
        The parameter `n_estimators` must be divisible by `subforest_size`. Should typically be a small constant.

    n_jobs : int or None, default -1
        The number of parallel jobs to be used for parallelism; follows joblib semantics.
        `n_jobs=-1` means all available cpu cores. `n_jobs=None` means no parallelism.

    random_state : int, RandomState instance, or None, default None
        Controls the randomness of the estimator. The features are always
        randomly permuted at each split. When ``max_features < n_features``, the algorithm will
        select ``max_features`` at random at each split before finding the best
        split among them. But the best found split may vary across different
        runs, even if ``max_features=n_features``. That is the case, if the
        improvement of the criterion is identical for several splits and one
        split has to be selected at random. To obtain a deterministic behaviour
        during fitting, ``random_state`` has to be fixed to an integer.

    verbose : int, default 0
        Controls the verbosity when fitting and predicting.

    allow_missing: bool
        Whether to allow missing values in W. If True, will need to supply model_y, model_y that can handle
        missing values.

    use_ray: bool, default False
        Whether to use Ray to parallelize the cross-validation step. If True, Ray must be installed.

    ray_remote_func_options : dict, default None
        Options to pass to the remote function when using Ray.
        See https://docs.ray.io/en/latest/ray-core/api/doc/ray.remote.html

    Examples
    --------
    A simple example with the default models and discrete treatment:

    .. testcode::
        :hide:

        import numpy as np
        import scipy.special
        np.set_printoptions(suppress=True)

    .. testcode::

        from econml.dml import CausalForestDML

        np.random.seed(123)
        X = np.random.normal(size=(1000, 5))
        T = np.random.binomial(1, scipy.special.expit(X[:, 0]))
        y = (1 + .5*X[:, 0]) * T + X[:, 0] + np.random.normal(size=(1000,))
        est = CausalForestDML(discrete_treatment=True)
        est.fit(y, T, X=X, W=None)

    >>> est.effect(X[:3])
    array([0.62769..., 1.64575..., 0.68497...])
    >>> est.effect_interval(X[:3])
    (array([0.18798..., 1.17144..., 0.10788...]),
    array([1.06739..., 2.12006..., 1.26205...]))

    Attributes
    ----------
    ate_ : ndarray of shape (n_outcomes, n_treatments)
        The average constant marginal treatment effect of each treatment for each outcome,
        averaged over the training data and with a doubly robust correction. Available only
        when `discrete_treatment=True` and `drate=True`.
    ate_stderr_ : ndarray of shape (n_outcomes, n_treatments)
        The standard error of the `ate_` attribute.
    feature_importances_ : ndarray of shape (n_features,)
        The feature importances based on the amount of parameter heterogeneity they create.
        The higher, the more important the feature.
        The importance of a feature is computed as the (normalized) total heterogeneity that the feature
        creates. Each split that the feature was chosen adds::

            parent_weight * (left_weight * right_weight)
                * mean((value_left[k] - value_right[k])**2) / parent_weight**2

        to the importance of the feature. Each such quantity is also weighted by the depth of the split.
        By default splits below `max_depth=4` are not used in this calculation and also each split
        at depth `depth`, is re-weighted by 1 / (1 + `depth`)**2.0. See the method ``feature_importances``
        for a method that allows one to change these defaults.

    References
    ----------
    .. [cfdml1] Athey, Susan, Julie Tibshirani, and Stefan Wager. "Generalized random forests."
        The Annals of Statistics 47.2 (2019): 1148-1178
        https://arxiv.org/pdf/1610.01271.pdf

    """
    def __init__(self, *, model_y=..., model_t=..., featurizer=..., treatment_featurizer=..., discrete_outcome=..., discrete_treatment=..., categories=..., cv=..., mc_iters=..., mc_agg=..., drate=..., n_estimators=..., criterion=..., max_depth=..., min_samples_split=..., min_samples_leaf=..., min_weight_fraction_leaf=..., min_var_fraction_leaf=..., min_var_leaf_on_val=..., max_features=..., min_impurity_decrease=..., max_samples=..., min_balancedness_tol=..., honest=..., inference=..., fit_intercept=..., subforest_size=..., n_jobs=..., random_state=..., verbose=..., allow_missing=..., use_ray=..., ray_remote_func_options=...) -> None:
        ...
    
    @property
    def tunable_params(self): # -> list[str]:
        ...
    
    def tune(self, Y, T, *, X=..., W=..., sample_weight=..., groups=..., params=...): # -> Self:
        """
        Tunes the major hyperparameters of the final stage causal forest based on out-of-sample R-score performance.

        It trains small forests of size 100 trees on a grid of parameters and tests the
        out of sample R-score. After the function is called, then all parameters of `self` have been
        set to the optimal hyperparameters found. The estimator however remains un-fitted, so you need to
        call fit afterwards to fit the estimator with the chosen hyperparameters. The list of tunable parameters
        can be accessed via the property `tunable_params`.

        Parameters
        ----------
        Y: (n × d_y) matrix or vector of length n
            Outcomes for each sample
        T: (n × dₜ) matrix or vector of length n
            Treatments for each sample
        X: (n × dₓ) matrix
            Features for each sample
        W:  (n × d_w) matrix, optional
            Controls for each sample
        sample_weight:  (n,) vector, optional
            Weights for each row
        groups: (n,) vector, optional
            All rows corresponding to the same group will be kept together during splitting.
            If groups is not None, the `cv` argument passed to this class's initializer
            must support a 'groups' argument to its split method.
        params: dict or 'auto', default 'auto'
            A dictionary that contains the grid of hyperparameters to try, i.e.
            {'param1': [value1, value2, ...], 'param2': [value1, value2, ...], ...}
            If `params='auto'`, then a default grid is used.

        Returns
        -------
        self : CausalForestDML object
            The tuned causal forest object. This is the same object (not a copy) as the original one, but where
            all parameters of the object have been set to the best performing parameters from the tuning grid.
        """
        ...
    
    def sensitivity_summary(self, null_hypothesis=..., alpha=..., c_y=..., c_t=..., rho=..., decimals=...): # -> Summary:
        """
        Generate a summary of the sensitivity analysis for the ATE.

        Parameters
        ----------
        null_hypothesis: float, default 0
            The null_hypothesis value for the ATE.

        alpha: float, default 0.05
            The significance level for the sensitivity interval.

        c_y: float, default 0.05
            The level of confounding in the outcome. Ranges from 0 to 1.

        c_d: float, default 0.05
            The level of confounding in the treatment. Ranges from 0 to 1.

        decimals: int, default 3
            Number of decimal places to round each column to.

        """
        ...
    
    def sensitivity_interval(self, alpha=..., c_y=..., c_t=..., rho=..., interval_type=...): # -> tuple[NDArray[Any] | Any, NDArray[Any] | Any]:
        """
        Calculate the sensitivity interval for the ATE.

        The sensitivity interval is the range of values for the ATE that are
        consistent with the observed data, given a specified level of confounding.

        Can only be calculated when Y and T are single arrays, and T is binary or continuous.

        Based on [Chernozhukov2022]_

        Parameters
        ----------
        alpha: float, default 0.05
            The significance level for the sensitivity interval.

        c_y: float, default 0.05
            The level of confounding in the outcome. Ranges from 0 to 1.

        c_d: float, default 0.05
            The level of confounding in the treatment. Ranges from 0 to 1.

        interval_type: str, default 'ci'
            The type of interval to return. Can be 'ci' or 'theta'

        Returns
        -------
        (lb, ub): tuple of floats
            sensitivity interval for the ATE
        """
        ...
    
    def robustness_value(self, null_hypothesis=..., alpha=..., interval_type=...): # -> float | Literal[0]:
        """
        Calculate the robustness value for the ATE.

        The robustness value is the level of confounding (between 0 and 1) in
        *both* the treatment and outcome that would result in enough omitted variable bias such that
        we can no longer reject the null hypothesis. When null_hypothesis is the default of 0, the robustness value
        has the interpretation that it is the level of confounding that would make the
        ATE statistically insignificant.

        A higher value indicates a more robust estimate.

        Returns 0 if the original interval already includes the null_hypothesis.

        Can only be calculated when Y and T are single arrays, and T is binary or continuous.

        Based on [Chernozhukov2022]_

        Parameters
        ----------
        null_hypothesis: float, default 0
            The null_hypothesis value for the ATE.

        alpha: float, default 0.05
            The significance level for the robustness value.

        interval_type: str, default 'ci'
            The type of interval to return. Can be 'ci' or 'theta'

        Returns
        -------
        float
            The robustness value
        """
        ...
    
    def fit(self, Y, T, *, X=..., W=..., sample_weight=..., groups=..., cache_values=..., inference=...):
        """
        Estimate the counterfactual model from data, i.e. estimates functions τ(·,·,·), ∂τ(·,·).

        Parameters
        ----------
        Y: (n × d_y) matrix or vector of length n
            Outcomes for each sample
        T: (n × dₜ) matrix or vector of length n
            Treatments for each sample
        X: (n × dₓ) matrix
            Features for each sample
        W:  (n × d_w) matrix, optional
            Controls for each sample
        sample_weight : (n,) array_like or None
            Individual weights for each sample. If None, it assumes equal weight.
        groups: (n,) vector, optional
            All rows corresponding to the same group will be kept together during splitting.
            If groups is not None, the `cv` argument passed to this class's initializer
            must support a 'groups' argument to its split method.
        cache_values: bool, default False
            Whether to cache inputs and first stage results, which will allow refitting a different final model
        inference: str, :class:`.Inference` instance, or None
            Method for performing inference.  This estimator supports 'bootstrap'
            (or an instance of :class:`.BootstrapInference`), 'blb' or 'auto'
            (for Bootstrap-of-Little-Bags based inference)

        Returns
        -------
        self
        """
        ...
    
    def refit_final(self, *, inference=...): # -> Self:
        ...
    
    def feature_importances(self, max_depth=..., depth_decay_exponent=...):
        ...
    
    def summary(self, alpha=..., value=..., decimals=..., feature_names=..., treatment_names=..., output_names=...): # -> Summary | None:
        """
        Get a summary of coefficient and intercept in the linear model of the constant marginal treatment effect.

        Parameters
        ----------
        alpha:  float in [0, 1], default 0.05
            The overall level of confidence of the reported interval.
            The alpha/2, 1-alpha/2 confidence interval is reported.
        value: float, default 0
            The mean value of the metric you'd like to test under null hypothesis.
        decimals: int, default 3
            Number of decimal places to round each column to.
        feature_names: list of str, optional
            The input of the feature names
        treatment_names: list of str, optional
            The names of the treatments
        output_names: list of str, optional
            The names of the outputs

        Returns
        -------
        smry : Summary instance
            this holds the summary tables and text, which can be printed or
            converted to various output formats.
        """
        ...
    
    def shap_values(self, X, *, feature_names=..., treatment_names=..., output_names=..., background_samples=...): # -> dict[Any, dict[Any, Any]]:
        ...
    
    def ate__inference(self): # -> NormalInferenceResults:
        """
        Get inference results for the average treatment effect over the training data.

        Returns
        -------
        ate__inference : NormalInferenceResults
            Inference results information for the `ate_` attribute, which is the average
            constant marginal treatment effect of each treatment for each outcome, averaged
            over the training data and with a doubly robust correction.
            Available only when `discrete_treatment=True` and `drate=True`.
        """
        ...
    
    @property
    def ate_(self):
        ...
    
    @property
    def ate_stderr_(self):
        ...
    
    def att__inference(self, *, T): # -> NormalInferenceResults:
        """
        Get inference results for the average treatment effect on the treated for the training data.

        Parameters
        ----------
        T : int
            The index of the treatment for which to get the ATT. It corresponds to the
            lexicographic rank of the discrete input treatments.

        Returns
        -------
        att__inference : NormalInferenceResults
            Inference results information for the `att_` attribute, which is the average
            constant marginal treatment effect of each treatment for each outcome, averaged
            over the training data treated with treatment T and with a doubly robust correction.
            Available only when `discrete_treatment=True` and `drate=True`.
        """
        ...
    
    def att_(self, *, T):
        """
        Get the average treatment effect on the treated for the training data.

        Parameters
        ----------
        T : int
            The index of the treatment for which to get the ATT. It corresponds to the
            lexicographic rank of the discrete input treatments.

        Returns
        -------
        att_ : ndarray (n_y, n_t)
            The average constant marginal treatment effect of each treatment for each outcome, averaged
            over the training data treated with treatment T and with a doubly robust correction.
            Singleton dimensions are dropped if input variable was a vector.
        """
        ...
    
    def att_stderr_(self, *, T):
        """
        Get the standard error of the average treatment effect on the treated in the training data.

        Parameters
        ----------
        T : int
            The index of the treatment for which to get the ATT. It corresponds to the
            lexicographic rank of the discrete input treatments.

        Returns
        -------
        att_stderr_ : ndarray (n_y, n_t)
            The standard error of the corresponding `att_`
        """
        ...
    
    @property
    def feature_importances_(self):
        ...
    
    @property
    def model_final(self): # -> MultiOutputGRF:
        ...
    
    @model_final.setter
    def model_final(self, model): # -> None:
        ...
    
    def __len__(self):
        """Return the number of estimators in the ensemble."""
        ...
    
    def __getitem__(self, index):
        """Return the index'th estimator in the ensemble."""
        ...
    
    def __iter__(self):
        """Return iterator over estimators in the ensemble."""
        ...
    


