"""
This type stub file was generated by pyright.
"""

SensitivityParams = ...
def sensitivity_summary(theta, sigma, nu, cov, null_hypothesis=..., alpha=..., c_y=..., c_t=..., rho=..., decimals=...): # -> Summary:
    ...

def sensitivity_interval(theta, sigma, nu, cov, alpha, c_y, c_t, rho, interval_type=...): # -> tuple[NDArray[Any] | Any, NDArray[Any] | Any]:
    """Calculate the sensitivity interval."""
    ...

def RV(theta, sigma, nu, cov, alpha, null_hypothesis=..., interval_type=...): # -> float | Literal[0]:
    """
    Calculate the robustness value.

    The robustness value is the degree of confounding of *both* the
    treatment and the outcome that still produces an interval
    that excludes zero.

    When null_hypothesis is default of zero, we're looking for a value of r
    such that the sensitivity bounds just touch zero.

    Returns
    -------
    float
        The robustness value - the level of confounding (between 0 and 1) that would make
        the ATE reach the null_hypothesis. A higher value indicates
        a more robust estimate.
        Returns 0 if the original interval already includes the null_hypothesis.

    Notes
    -----
    This function uses a binary search approach to find the value of r where the
    sensitivity interval just touches zero.
    """
    ...

def dml_sensitivity_values(t_res, y_res): # -> SensitivityParams:
    ...

def dr_sensitivity_values(Y, T, y_pred, t_pred): # -> SensitivityParams:
    ...

