"""
This type stub file was generated by pyright.
"""

import abc

"""Base classes for all CATE estimators."""
class BaseCateEstimator(metaclass=abc.ABCMeta):
    """Base class for all CATE estimators in this package."""
    @abc.abstractmethod
    def fit(self, *args, inference=..., **kwargs):
        """
        Estimate the counterfactual model from data.

        That is, estimates functions :math:`\\tau(X, T0, T1)`, :math:`\\partial \\tau(T, X)`.

        Note that the signature of this method may vary in subclasses (e.g. classes that don't
        support instruments will not allow a `Z` argument)

        Parameters
        ----------
        Y: (n, d_y) matrix or vector of length n
            Outcomes for each sample
        T: (n, d_t) matrix or vector of length n
            Treatments for each sample
        X:  (n, d_x) matrix, optional
            Features for each sample
        W:  (n, d_w) matrix, optional
            Controls for each sample
        Z:  (n, d_z) matrix, optional
            Instruments for each sample
        inference: str or :class:`.Inference` instance, optional
            Method for performing inference.  All estimators support ``'bootstrap'``
            (or an instance of :class:`.BootstrapInference`), some support other methods as well.

        Returns
        -------
        self

        """
        ...
    
    @abc.abstractmethod
    def effect(self, X=..., *, T0, T1):
        """
        Calculate the heterogeneous treatment effect :math:`\\tau(X, T0, T1)`.

        The effect is calculated between the two treatment points
        conditional on a vector of features on a set of m test samples :math:`\\{T0_i, T1_i, X_i\\}`.

        Parameters
        ----------
        T0: (m, d_t) matrix or vector of length m
            Base treatments for each sample
        T1: (m, d_t) matrix or vector of length m
            Target treatments for each sample
        X:  (m, d_x) matrix, optional
            Features for each sample

        Returns
        -------
        τ: (m, d_y) matrix
            Heterogeneous treatment effects on each outcome for each sample
            Note that when Y is a vector rather than a 2-dimensional array, the corresponding
            singleton dimension will be collapsed (so this method will return a vector)
        """
        ...
    
    @abc.abstractmethod
    def marginal_effect(self, T, X=...):
        """
        Calculate the heterogeneous marginal effect :math:`\\partial\\tau(T, X)`.

        The marginal effect is calculated around a base treatment
        point conditional on a vector of features on a set of m test samples :math:`\\{T_i, X_i\\}`.

        Parameters
        ----------
        T: (m, d_t) matrix
            Base treatments for each sample
        X:  (m, d_x) matrix, optional
            Features for each sample

        Returns
        -------
        grad_tau: (m, d_y, d_t) array
            Heterogeneous marginal effects on each outcome for each sample
            Note that when Y or T is a vector rather than a 2-dimensional array,
            the corresponding singleton dimensions in the output will be collapsed
            (e.g. if both are vectors, then the output of this method will also be a vector)
        """
        ...
    
    def ate(self, X=..., *, T0, T1): # -> Incomplete:
        """
        Calculate the average treatment effect :math:`E_X[\\tau(X, T0, T1)]`.

        The effect is calculated between the two treatment points and is averaged over
        the population of X variables.

        Parameters
        ----------
        T0: (m, d_t) matrix or vector of length m
            Base treatments for each sample
        T1: (m, d_t) matrix or vector of length m
            Target treatments for each sample
        X:  (m, d_x) matrix, optional
            Features for each sample

        Returns
        -------
        τ: float or (d_y,) array
            Average treatment effects on each outcome
            Note that when Y is a vector rather than a 2-dimensional array, the result will be a scalar
        """
        ...
    
    def cate_feature_names(self, feature_names=...): # -> list[str] | None:
        """Public interface for getting feature names.

        To be overriden by estimators that apply transformations the input features.

        Parameters
        ----------
        feature_names: list of str of length X.shape[1] or None
            The names of the input features. If None and X is a dataframe, it defaults to the column names
            from the dataframe.

        Returns
        -------
        out_feature_names: list of str or None
            Returns feature names.
        """
        ...
    
    def cate_output_names(self, output_names=...): # -> list[str] | None:
        """
        Public interface for getting output names.

        To be overriden by estimators that apply transformations the outputs.

        Parameters
        ----------
        output_names: list of str of length Y.shape[1] or None
            The names of the outcomes. If None and the Y passed to fit was a dataframe,
            it defaults to the column names from the dataframe.

        Returns
        -------
        output_names: list of str
            Returns output names.
        """
        ...
    
    def cate_treatment_names(self, treatment_names=...): # -> list[str] | None:
        """
        Public interface for getting treatment names.

        To be overriden by estimators that apply transformations the treatments.

        Parameters
        ----------
        treatment_names: list of str of length T.shape[1] or None
            The names of the treatments. If None and the T passed to fit was a dataframe,
            it defaults to the column names from the dataframe.

        Returns
        -------
        treatment_names: list of str
            Returns treatment names.
        """
        ...
    
    def marginal_ate(self, T, X=...): # -> Incomplete:
        """
        Calculate the average marginal effect :math:`E_{T, X}[\\partial\\tau(T, X)]`.

        The marginal effect is calculated around a base treatment
        point and averaged over the population of X.

        Parameters
        ----------
        T: (m, d_t) matrix
            Base treatments for each sample
        X:  (m, d_x) matrix, optional
            Features for each sample

        Returns
        -------
        grad_tau: (d_y, d_t) array
            Average marginal effects on each outcome
            Note that when Y or T is a vector rather than a 2-dimensional array,
            the corresponding singleton dimensions in the output will be collapsed
            (e.g. if both are vectors, then the output of this method will be a scalar)
        """
        ...
    
    @_defer_to_inference
    def effect_interval(self, X=..., *, T0=..., T1=..., alpha=...):
        """
        Confidence intervals for the quantities :math:`\\tau(X, T0, T1)` produced by the model.

        Available only when ``inference`` is not ``None``, when
        calling the fit method.

        Parameters
        ----------
        X:  (m, d_x) matrix, optional
            Features for each sample
        T0:  (m, d_t) matrix or vector of length m, default 0
            Base treatments for each sample
        T1:  (m, d_t) matrix or vector of length m, default 1
            Target treatments for each sample
        alpha:  float in [0, 1], default 0.05
            The overall level of confidence of the reported interval.
            The alpha/2, 1-alpha/2 confidence interval is reported.

        Returns
        -------
        lower, upper : tuple(type of :meth:`effect(X, T0, T1)<effect>`, type of :meth:`effect(X, T0, T1))<effect>` )
            The lower and the upper bounds of the confidence interval for each quantity.
        """
        ...
    
    @_defer_to_inference
    def effect_inference(self, X=..., *, T0=..., T1=...):
        """
        Inference results for the quantities :math:`\\tau(X, T0, T1)` produced by the model.

        Available only when ``inference`` is not ``None``, when
        calling the fit method.

        Parameters
        ----------
        X:  (m, d_x) matrix, optional
            Features for each sample
        T0:  (m, d_t) matrix or vector of length m, default 0
            Base treatments for each sample
        T1:  (m, d_t) matrix or vector of length m, default 1
            Target treatments for each sample

        Returns
        -------
        InferenceResults: object
            The inference results instance contains prediction and prediction standard error and
            can on demand calculate confidence interval, z statistic and p value. It can also output
            a dataframe summary of these inference results.
        """
        ...
    
    @_defer_to_inference
    def marginal_effect_interval(self, T, X=..., *, alpha=...):
        """
        Confidence intervals for the quantities :math:`\\partial \\tau(T, X)` produced by the model.

        Available only when ``inference`` is not ``None``, when
        calling the fit method.

        Parameters
        ----------
        T: (m, d_t) matrix
            Base treatments for each sample
        X: (m, d_x) matrix, optional
            Features for each sample
        alpha:  float in [0, 1], default 0.05
            The overall level of confidence of the reported interval.
            The alpha/2, 1-alpha/2 confidence interval is reported.

        Returns
        -------
        lower, upper : tuple(type of :meth:`marginal_effect(T, X)<marginal_effect>`, \
                             type of :meth:`marginal_effect(T, X)<marginal_effect>` )
            The lower and the upper bounds of the confidence interval for each quantity.
        """
        ...
    
    @_defer_to_inference
    def marginal_effect_inference(self, T, X=...):
        """
        Inference results for the quantities :math:`\\partial \\tau(T, X)` produced by the model.

        Available only when ``inference`` is not ``None``, when
        calling the fit method.

        Parameters
        ----------
        T: (m, d_t) matrix
            Base treatments for each sample
        X: (m, d_x) matrix, optional
            Features for each sample

        Returns
        -------
        InferenceResults: object
            The inference results instance contains prediction and prediction standard error and
            can on demand calculate confidence interval, z statistic and p value. It can also output
            a dataframe summary of these inference results.
        """
        ...
    
    @_defer_to_inference
    def ate_interval(self, X=..., *, T0, T1, alpha=...):
        """
        Confidence intervals for the quantity :math:`E_X[\\tau(X, T0, T1)]` produced by the model.

        Available only when ``inference`` is not ``None``, when
        calling the fit method.

        Parameters
        ----------
        X:  (m, d_x) matrix, optional
            Features for each sample
        T0:  (m, d_t) matrix or vector of length m, default 0
            Base treatments for each sample
        T1:  (m, d_t) matrix or vector of length m, default 1
            Target treatments for each sample
        alpha:  float in [0, 1], default 0.05
            The overall level of confidence of the reported interval.
            The alpha/2, 1-alpha/2 confidence interval is reported.

        Returns
        -------
        lower, upper : tuple(type of :meth:`ate(X, T0, T1)<ate>`, type of :meth:`ate(X, T0, T1))<ate>` )
            The lower and the upper bounds of the confidence interval for each quantity.
        """
        ...
    
    @_defer_to_inference
    def ate_inference(self, X=..., *, T0, T1):
        """
        Inference results for the quantity :math:`E_X[\\tau(X, T0, T1)]` produced by the model.

        Available only when ``inference`` is not ``None``, when
        calling the fit method.

        Parameters
        ----------
        X:  (m, d_x) matrix, optional
            Features for each sample
        T0:  (m, d_t) matrix or vector of length m, default 0
            Base treatments for each sample
        T1:  (m, d_t) matrix or vector of length m, default 1
            Target treatments for each sample

        Returns
        -------
        PopulationSummaryResults: object
            The inference results instance contains prediction and prediction standard error and
            can on demand calculate confidence interval, z statistic and p value. It can also output
            a dataframe summary of these inference results.
        """
        ...
    
    @_defer_to_inference
    def marginal_ate_interval(self, T, X=..., *, alpha=...):
        """
        Confidence intervals for the quantities :math:`E_{T,X}[\\partial \\tau(T, X)]` produced by the model.

        Available only when ``inference`` is not ``None``, when
        calling the fit method.

        Parameters
        ----------
        T: (m, d_t) matrix
            Base treatments for each sample
        X: (m, d_x) matrix, optional
            Features for each sample
        alpha:  float in [0, 1], default 0.05
            The overall level of confidence of the reported interval.
            The alpha/2, 1-alpha/2 confidence interval is reported.

        Returns
        -------
        lower, upper : tuple(type of :meth:`marginal_ate(T, X)<marginal_ate>`, \
                             type of :meth:`marginal_ate(T, X)<marginal_ate>` )
            The lower and the upper bounds of the confidence interval for each quantity.
        """
        ...
    
    @_defer_to_inference
    def marginal_ate_inference(self, T, X=...):
        """
        Inference results for the quantities :math:`E_{T,X}[\\partial \\tau(T, X)]` produced by the model.

        Available only when ``inference`` is not ``None``, when
        calling the fit method.

        Parameters
        ----------
        T: (m, d_t) matrix
            Base treatments for each sample
        X: (m, d_x) matrix, optional
            Features for each sample

        Returns
        -------
        PopulationSummaryResults: object
            The inference results instance contains prediction and prediction standard error and
            can on demand calculate confidence interval, z statistic and p value. It can also output
            a dataframe summary of these inference results.
        """
        ...
    
    @property
    def dowhy(self): # -> DoWhyWrapper:
        """
        Get a :class:`.DoWhyWrapper` to enable functionality (e.g. causal graph, refutation test, etc.) from dowhy.

        Returns
        -------
        DoWhyWrapper: instance
            An instance of :class:`.DoWhyWrapper`
        """
        ...
    


class LinearCateEstimator(BaseCateEstimator):
    """Base class for CATE estimators in this package where the outcome is linear given some treatment featurization."""
    _original_treatment_featurizer = ...
    @abc.abstractmethod
    def const_marginal_effect(self, X=...):
        """
        Calculate the constant marginal CATE :math:`\\theta(·)`.

        The marginal effect is conditional on a vector of
        features on a set of m test samples X[i].

        Parameters
        ----------
        X: (m, d_x) matrix, optional
            Features for each sample.

        Returns
        -------
        theta: (m, d_y, d_f_t) matrix or (d_y, d_f_t) matrix if X is None where d_f_t is \
            the dimension of the featurized treatment. If treatment_featurizer is None, d_f_t = d_t.
            Constant marginal CATE of each featurized treatment on each outcome for each sample X[i].
            Note that when Y or featurized-T (or T if treatment_featurizer is None) is a vector
            rather than a 2-dimensional array, the corresponding singleton dimensions in the output will be collapsed
            (e.g. if both are vectors, then the output of this method will also be a vector)
        """
        ...
    
    def effect(self, X=..., *, T0, T1): # -> Any:
        """
        Calculate the heterogeneous treatment effect :math:`\\tau(X, T0, T1)`.

        The effect is calculated between the two treatment points
        conditional on a vector of features on a set of m test samples :math:`\\{T0_i, T1_i, X_i\\}`.
        Since this class assumes a linear effect, only the difference between T0ᵢ and T1ᵢ
        matters for this computation.

        Parameters
        ----------
        T0: (m, d_t) matrix
            Base treatments for each sample
        T1: (m, d_t) matrix
            Target treatments for each sample
        X:  (m, d_x) matrix, optional
            Features for each sample

        Returns
        -------
        effect: (m, d_y) matrix (or length m vector if Y was a vector)
            Heterogeneous treatment effects on each outcome for each sample.
            Note that when Y is a vector rather than a 2-dimensional array, the corresponding
            singleton dimension will be collapsed (so this method will return a vector)
        """
        ...
    
    def marginal_effect(self, T, X=...): # -> Any | NDArray[Any]:
        """
        Calculate the heterogeneous marginal effect :math:`\\partial\\tau(T, X)`.

        The marginal effect is calculated around a base treatment
        point conditional on a vector of features on a set of m test samples :math:`\\{T_i, X_i\\}`.
        If treatment_featurizer is None, the base treatment is ignored in this calculation and the result
        is equivalent to const_marginal_effect.

        Parameters
        ----------
        T: (m, d_t) matrix
            Base treatments for each sample
        X:  (m, d_x) matrix, optional
            Features for each sample

        Returns
        -------
        grad_tau: (m, d_y, d_t) array
            Heterogeneous marginal effects on each outcome for each sample
            Note that when Y or T is a vector rather than a 2-dimensional array,
            the corresponding singleton dimensions in the output will be collapsed
            (e.g. if both are vectors, then the output of this method will also be a vector)
        """
        ...
    
    def marginal_effect_interval(self, T, X=..., *, alpha=...): # -> Any | tuple[NDArray[Any], ...]:
        ...
    
    def marginal_effect_inference(self, T, X=...): # -> Any:
        ...
    
    @BaseCateEstimator._defer_to_inference
    def const_marginal_effect_interval(self, X=..., *, alpha=...):
        """
        Confidence intervals for the quantities :math:`\\theta(X)` produced by the model.

        Available only when ``inference`` is not ``None``, when
        calling the fit method.

        Parameters
        ----------
        X: (m, d_x) matrix, optional
            Features for each sample
        alpha:  float in [0, 1], default 0.05
            The overall level of confidence of the reported interval.
            The alpha/2, 1-alpha/2 confidence interval is reported.

        Returns
        -------
        lower, upper : tuple(type of :meth:`const_marginal_effect(X)<const_marginal_effect>` ,\
                             type of :meth:`const_marginal_effect(X)<const_marginal_effect>` )
            The lower and the upper bounds of the confidence interval for each quantity.
        """
        ...
    
    @BaseCateEstimator._defer_to_inference
    def const_marginal_effect_inference(self, X=...):
        """
        Inference results for the quantities :math:`\\theta(X)` produced by the model.

        Available only when ``inference`` is not ``None``, when
        calling the fit method.

        Parameters
        ----------
        X: (m, d_x) matrix, optional
            Features for each sample

        Returns
        -------
        InferenceResults: object
            The inference results instance contains prediction and prediction standard error and
            can on demand calculate confidence interval, z statistic and p value. It can also output
            a dataframe summary of these inference results.
        """
        ...
    
    def const_marginal_ate(self, X=...): # -> Incomplete:
        """
        Calculate the average constant marginal CATE :math:`E_X[\\theta(X)]`.

        Parameters
        ----------
        X: (m, d_x) matrix, optional
            Features for each sample.

        Returns
        -------
        theta: (d_y, d_f_t) matrix where d_f_t is the dimension of the featurized treatment. \
            If treatment_featurizer is None, d_f_t = d_t.
            Average constant marginal CATE of each treatment on each outcome.
            Note that when Y or featurized-T (or T if treatment_featurizer is None) is a vector
            rather than a 2-dimensional array, the corresponding singleton dimensions in the output will be collapsed
            (e.g. if both are vectors, then the output of this method will also be a scalar)
        """
        ...
    
    @BaseCateEstimator._defer_to_inference
    def const_marginal_ate_interval(self, X=..., *, alpha=...):
        """
        Confidence intervals for the quantities :math:`E_X[\\theta(X)]` produced by the model.

        Available only when ``inference`` is not ``None``, when
        calling the fit method.

        Parameters
        ----------
        X: (m, d_x) matrix, optional
            Features for each sample
        alpha:  float in [0, 1], default 0.05
            The overall level of confidence of the reported interval.
            The alpha/2, 1-alpha/2 confidence interval is reported.

        Returns
        -------
        lower, upper : tuple(type of :meth:`const_marginal_ate(X)<const_marginal_ate>` ,\
                             type of :meth:`const_marginal_ate(X)<const_marginal_ate>` )
            The lower and the upper bounds of the confidence interval for each quantity.
        """
        ...
    
    @BaseCateEstimator._defer_to_inference
    def const_marginal_ate_inference(self, X=...): # -> None:
        """
        Inference results for the quantities :math:`E_X[\\theta(X)]` produced by the model.

        Available only when ``inference`` is not ``None``, when
        calling the fit method.

        Parameters
        ----------
        X: (m, d_x) matrix, optional
            Features for each sample

        Returns
        -------
        PopulationSummaryResults: object
            The inference results instance contains prediction and prediction standard error and
            can on demand calculate confidence interval, z statistic and p value. It can also output
            a dataframe summary of these inference results.
        """
        ...
    
    def marginal_ate(self, T, X=...): # -> Incomplete:
        ...
    
    @BaseCateEstimator._defer_to_inference
    def marginal_ate_interval(self, T, X=..., *, alpha=...):
        ...
    
    @BaseCateEstimator._defer_to_inference
    def marginal_ate_inference(self, T, X=...):
        ...
    
    def shap_values(self, X, *, feature_names=..., treatment_names=..., output_names=..., background_samples=...): # -> dict[Any, dict[Any, Any]]:
        """
        Shap value for the final stage models (const_marginal_effect).

        Parameters
        ----------
        X: (m, d_x) matrix
            Features for each sample. Should be in the same shape of fitted X in final stage.
        feature_names:  list of str of length X.shape[1], optional
            The names of input features.
        treatment_names:  list, optional
            The name of featurized treatment. In discrete treatment scenario, the name should not include the name of
            the baseline treatment (i.e. the control treatment, which by default is the alphabetically smaller)
        output_names:  list, optional
            The name of the outcome.
        background_samples: int , default 100
            How many samples to use to compute the baseline effect. If None then all samples are used.

        Returns
        -------
        shap_outs: nested dictionary of Explanation object
            A nested dictionary by using each output name (e.g. 'Y0', 'Y1', ... when `output_names=None`) and
            each treatment name (e.g. 'T0', 'T1', ... when `treatment_names=None`) as key
            and the shap_values explanation object as value. If the input data at fit time also contain metadata,
            (e.g. are pandas DataFrames), then the column metatdata for the treatments, outcomes and features
            are used instead of the above defaults (unless the user overrides with explicitly passing the
            corresponding names).
        """
        ...
    


class TreatmentExpansionMixin(BaseCateEstimator):
    """
    Mixin which automatically handles promotions of scalar treatments to the appropriate shape.

    Also applies treatment featurization for discrete treatments and user-specified treatment transformers.
    """
    transformer = ...
    _original_treatment_featurizer = ...
    def cate_treatment_names(self, treatment_names=...): # -> list[str] | None:
        """
        Get treatment names.

        If the treatment is discrete or featurized, it will return expanded treatment names.

        Parameters
        ----------
        treatment_names:  list of str of length T.shape[1], optional
            The names of the treatments. If None and the T passed to fit was a dataframe,
            it defaults to the column names from the dataframe.

        Returns
        -------
        out_treatment_names: list of str
            Returns (possibly expanded) treatment names.
        """
        ...
    
    def effect(self, X=..., *, T0=..., T1=...):
        ...
    
    def ate(self, X=..., *, T0=..., T1=...): # -> Incomplete:
        ...
    
    def ate_interval(self, X=..., *, T0=..., T1=..., alpha=...):
        ...
    
    def ate_inference(self, X=..., *, T0=..., T1=...):
        ...
    


class LinearModelFinalCateEstimatorMixin(BaseCateEstimator):
    """
    Base class for models where the final stage is a linear model.

    Such an estimator must implement a :attr:`model_final_` attribute that points
    to the fitted final :class:`.StatsModelsLinearRegression` object that
    represents the fitted CATE model. Also must implement :attr:`featurizer_` that points
    to the fitted featurizer and :attr:`bias_part_of_coef` that designates
    if the intercept is the first element of the :attr:`model_final_` coefficient.

    Attributes
    ----------
    bias_part_of_coef: bool
        Whether the CATE model's intercept is contained in the final model's ``coef_`` rather
        than as a separate ``intercept_``
    """
    featurizer = ...
    @property
    def bias_part_of_coef(self): # -> Literal[False]:
        ...
    
    @property
    def coef_(self):
        """
        Get the coefficients in the linear model of the constant marginal treatment effect.

        Returns
        -------
        coef: (n_x,) or (n_t, n_x) or (n_y, n_t, n_x) array_like
            Where n_x is the number of features that enter the final model (either the
            dimension of X or the dimension of featurizer.fit_transform(X) if the CATE
            estimator has a featurizer.), n_t is the number of treatments, n_y is
            the number of outcomes. Dimensions are omitted if the original input was
            a vector and not a 2D array. For binary treatment the n_t dimension is
            also omitted.
        """
        ...
    
    @property
    def intercept_(self): # -> ndarray[tuple[int], dtype[Any]] | None:
        """
        Get the intercept in the linear model of the constant marginal treatment effect.

        Returns
        -------
        intercept: float or (n_y,) or (n_y, n_t) array_like
            Where n_t is the number of treatments, n_y is
            the number of outcomes. Dimensions are omitted if the original input was
            a vector and not a 2D array. For binary treatment the n_t dimension is
            also omitted.
        """
        ...
    
    @BaseCateEstimator._defer_to_inference
    def coef__interval(self, *, alpha=...):
        """
        Get the confidence interval for coefficients in the linear model of the constant marginal treatment effect.

        Parameters
        ----------
        alpha:  float in [0, 1], default 0.05
            The overall level of confidence of the reported interval.
            The alpha/2, 1-alpha/2 confidence interval is reported.

        Returns
        -------
        lb, ub: tuple(type of :meth:`coef_()<coef_>`, type of :meth:`coef_()<coef_>`)
            The lower and upper bounds of the confidence interval for each quantity.
        """
        ...
    
    @BaseCateEstimator._defer_to_inference
    def coef__inference(self):
        """
        Get inference information for coefficients in the linear model of the constant marginal treatment effect.

        Returns
        -------
        InferenceResults: object
            The inference of the coefficients in the final linear model
        """
        ...
    
    @BaseCateEstimator._defer_to_inference
    def intercept__interval(self, *, alpha=...):
        """
        Get the confidence interval for the intercept in the linear model of the constant marginal treatment effect.

        Parameters
        ----------
        alpha:  float in [0, 1], default 0.05
            The overall level of confidence of the reported interval.
            The alpha/2, 1-alpha/2 confidence interval is reported.

        Returns
        -------
        lower, upper: tuple(type of :meth:`intercept_()<intercept_>`, type of :meth:`intercept_()<intercept_>`)
            The lower and upper bounds of the confidence interval.
        """
        ...
    
    @BaseCateEstimator._defer_to_inference
    def intercept__inference(self):
        """
        Get inference results for intercept in the linear model of the constant marginal treatment effect.

        Returns
        -------
        InferenceResults: object
            The inference of the intercept in the final linear model
        """
        ...
    
    def summary(self, alpha=..., value=..., decimals=..., feature_names=..., treatment_names=..., output_names=...): # -> Summary | None:
        """
        Get a summary of coefficient and intercept in the linear model of the constant marginal treatment effect.

        Parameters
        ----------
        alpha:  float in [0, 1], default 0.05
            The overall level of confidence of the reported interval.
            The alpha/2, 1-alpha/2 confidence interval is reported.
        value: float, default 0
            The mean value of the metric you'd like to test under null hypothesis.
        decimals: int, default 3
            Number of decimal places to round each column to.
        feature_names: list of str, optional
            The input of the feature names
        treatment_names: list of str, optional
            The names of the treatments
        output_names: list of str, optional
            The names of the outputs

        Returns
        -------
        smry : Summary instance
            this holds the summary tables and text, which can be printed or
            converted to various output formats.
        """
        ...
    
    def shap_values(self, X, *, feature_names=..., treatment_names=..., output_names=..., background_samples=...): # -> dict[Any, dict[Any, Any]]:
        ...
    


class StatsModelsCateEstimatorMixin(LinearModelFinalCateEstimatorMixin):
    """
    Mixin class that offers `inference='statsmodels'` options to the CATE estimator that inherits it.

    Such an estimator must implement a :attr:`model_final_` attribute that points
    to the fitted final :class:`.StatsModelsLinearRegression` object that
    represents the fitted CATE model. Also must implement :attr:`featurizer_` that points
    to the fitted featurizer and :attr:`bias_part_of_coef` that designates
    if the intercept is the first element of the :attr:`model_final_` coefficient.
    """
    ...


class DebiasedLassoCateEstimatorMixin(LinearModelFinalCateEstimatorMixin):
    """Mixin for cate models where the final stage is a debiased lasso model."""
    ...


class ForestModelFinalCateEstimatorMixin(BaseCateEstimator):
    @property
    def feature_importances_(self):
        ...
    


class LinearModelFinalCateEstimatorDiscreteMixin(BaseCateEstimator):
    """
    Base class for models where the final stage is a linear model.

    Subclasses must expose a ``fitted_models_final`` attribute
    returning an array of the fitted models for each non-control treatment
    """
    def coef_(self, T):
        """
        Get the coefficients in the linear model of the constant marginal treatment effect associated with treatment T.

        Parameters
        ----------
        T: alphanumeric
            The input treatment for which we want the coefficients.

        Returns
        -------
        coef: (n_x,) or (n_y, n_x) array_like
            Where n_x is the number of features that enter the final model (either the
            dimension of X or the dimension of featurizer.fit_transform(X) if the CATE
            estimator has a featurizer.)
        """
        ...
    
    def intercept_(self, T):
        """
        Get the intercept in the linear model of the constant marginal treatment effect associated with treatment T.

        Parameters
        ----------
        T: alphanumeric
            The input treatment for which we want the intercept.

        Returns
        -------
        intercept: float or (n_y,) array_like
        """
        ...
    
    @BaseCateEstimator._defer_to_inference
    def coef__interval(self, T, *, alpha=...):
        """
        Get the confidence interval for the coefficients in the linear model of the constant marginal treatment effect.

        Parameters
        ----------
        T: alphanumeric
            The input treatment for which we want the coefficients.
        alpha:  float in [0, 1], default 0.05
            The overall level of confidence of the reported interval.
            The alpha/2, 1-alpha/2 confidence interval is reported.

        Returns
        -------
        lower, upper: tuple(type of :meth:`coef_(T)<coef_>`, type of :meth:`coef_(T)<coef_>`)
            The lower and upper bounds of the confidence interval for each quantity.
        """
        ...
    
    @BaseCateEstimator._defer_to_inference
    def coef__inference(self, T):
        """
        Get inference results for the coefficients in the linear model of the constant marginal treatment effect.

        Parameters
        ----------
        T: alphanumeric
            The input treatment for which we want the coefficients.

        Returns
        -------
        InferenceResults: object
            The inference of the coefficients in the final linear model
        """
        ...
    
    @BaseCateEstimator._defer_to_inference
    def intercept__interval(self, T, *, alpha=...):
        """
        Get the intercept in the linear model of the constant marginal treatment effect.

        Parameters
        ----------
        T: alphanumeric
            The input treatment for which we want the intercept.
        alpha:  float in [0, 1], default 0.05
            The overall level of confidence of the reported interval.
            The alpha/2, 1-alpha/2 confidence interval is reported.

        Returns
        -------
        lower, upper: tuple(type of :meth:`intercept_(T)<intercept_>`, type of :meth:`intercept_(T)<intercept_>`)
            The lower and upper bounds of the confidence interval.
        """
        ...
    
    @BaseCateEstimator._defer_to_inference
    def intercept__inference(self, T):
        """
        Get inference results for the intercept in the linear model of the constant marginal treatment effect.

        Parameters
        ----------
        T: alphanumeric
            The input treatment for which we want the intercept.

        Returns
        -------
        InferenceResults: object
            The inference of the intercept in the final linear model

        """
        ...
    
    def summary(self, T, *, alpha=..., value=..., decimals=..., feature_names=..., treatment_names=..., output_names=...): # -> Summary | None:
        """
        Get a summary of coefficient and intercept in the linear model of the constant marginal treatment effect.

        Parameters
        ----------
        T: alphanumeric
            The input treatment for which we want the summary.
        alpha:  float in [0, 1], default 0.05
            The overall level of confidence of the reported interval.
            The alpha/2, 1-alpha/2 confidence interval is reported.
        value: float, default 0
            The mean value of the metric you'd like to test under null hypothesis.
        decimals: int, default 3
            Number of decimal places to round each column to.
        feature_names: list of str, optional
            The input of the feature names
        treatment_names: list of str, optional
            The names of the treatments
        output_names: list of str, optional
            The names of the outputs

        Returns
        -------
        smry : Summary instance
            this holds the summary tables and text, which can be printed or
            converted to various output formats.
        """
        ...
    


class StatsModelsCateEstimatorDiscreteMixin(LinearModelFinalCateEstimatorDiscreteMixin):
    """
    Mixin class that offers `inference='statsmodels'` options to the CATE estimator that inherits it.

    Such an estimator must implement a :attr:`model_final_` attribute that points
    to a :class:`.StatsModelsLinearRegression` object that is cloned to fit
    each discrete treatment target CATE model and a :attr:`fitted_models_final` attribute
    that returns the list of fitted final models that represent the CATE for each categorical treatment.
    """
    ...


class DebiasedLassoCateEstimatorDiscreteMixin(LinearModelFinalCateEstimatorDiscreteMixin):
    """Mixin for cate models where the final stage is a debiased lasso model."""
    ...


class ForestModelFinalCateEstimatorDiscreteMixin(BaseCateEstimator):
    def feature_importances_(self, T):
        ...
    


