from __future__ import annotations

import asyncio
import logging
from functools import lru_cache
from uuid import UUID

from fastapi import Depends, FastAPI, File, Header, HTTPException, Path, Security, UploadFile
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import Response
from fastapi.security import HTTPAuthorizationCredentials, HTTPBearer

from python.adapters.api.schemas import (
    CreateConversationResponse,
    InvokeRequest,
    InvokeResponse,
    UploadDatasetResponse,
)
from python.domain.models.errors import ConversationNotFoundError
from python.domain.service.auth_service import AuthService, AuthenticatedUser
from python.implementation.service.firebsae_auth_service import (
    AuthServiceError,
    FirebaseAuthService,
    InvalidTokenError,
)

from python.implementation.workflows.depinit import make_workflow_app
from python.implementation.workflows.workflow_app import WorkflowApp, WorkflowRequest

log = logging.getLogger(__name__)

_OPENAPI_TAGS = [
    {"name": "system", "description": "Health and service status endpoints."},
    {"name": "conversations", "description": "Create and advance authenticated workflow conversations."},
    {"name": "datasets", "description": "Upload CSV datasets for a conversation."},
    {"name": "artifacts", "description": "Download artifacts generated by the workflow."},
]

app = FastAPI(
    title="AitiaMed Copilot API",
    version="0.1.0",
    summary="Authenticated API for medical causal inference workflow interactions.",
    description=(
        "Upload a CSV dataset, invoke the causal workflow, and download generated artifacts.\n\n"
        "Authentication:\n"
        "- All `/v1/...` endpoints require a Firebase Bearer token.\n"
        "- `/healthz` is public.\n"
        "- The authenticated Firebase identity is mapped to the internal workflow `user_id`."
    ),
    openapi_tags=_OPENAPI_TAGS,
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # tighten in prod
    allow_credentials=False,
    allow_methods=["*"],
    allow_headers=["*"],
)

logging.basicConfig(level=logging.INFO)

bearer_scheme = HTTPBearer(
    auto_error=False,
    description="Firebase Bearer JWT. Paste the raw Firebase ID token.",
)

def _unauthorized(detail: str) -> HTTPException:
    return HTTPException(
        status_code=401,
        detail=detail,
        headers={"WWW-Authenticate": "Bearer"},
    )


@lru_cache(maxsize=1)
def get_workflow_app() -> WorkflowApp:
    return make_workflow_app()


@lru_cache(maxsize=1)
def get_auth_service() -> AuthService:
    return FirebaseAuthService(app=FirebaseAuthService.get_firebase_auth_default_app())


def get_authenticated_user(
    credentials: HTTPAuthorizationCredentials | None = Security(bearer_scheme),
    authorization: str | None = Header(default=None, include_in_schema=False),
) -> AuthenticatedUser:
    if authorization is None:
        raise _unauthorized("Missing Authorization header.")

    scheme, _, token = authorization.partition(" ")
    if scheme.lower() != "bearer":
        raise _unauthorized("Authorization header must use the Bearer scheme.")

    normalized_token = token.strip()
    if not normalized_token:
        raise _unauthorized("Bearer token is missing.")
    if credentials is None:
        raise _unauthorized("Invalid or expired bearer token.")

    try:
        return get_auth_service().verify_token_and_get_user(normalized_token)
    except (InvalidTokenError, ValueError) as exc:
        raise _unauthorized("Invalid or expired bearer token.") from exc
    except AuthServiceError as exc:
        log.exception("authentication failed")
        raise HTTPException(status_code=500, detail="authentication service unavailable") from exc
    except Exception as exc:
        log.exception("authentication failed")
        raise HTTPException(status_code=500, detail="authentication service unavailable") from exc


@app.get(
    "/healthz",
    tags=["system"],
    summary="Health check",
    description="Public endpoint used for service liveness and readiness checks.",
)
def healthz():
    return {"ok": True}


@app.get(
    path="/v1/conversations/{conversation_id}/artifacts/{artifact_id}",
    tags=["artifacts"],
    summary="Download an artifact",
    description="Downloads an artifact generated for the authenticated user's conversation.",
    response_description="Artifact bytes streamed inline.",
    responses={
        401: {"description": "Missing or invalid Bearer token."},
        404: {"description": "Artifact not found for this authenticated conversation."},
        500: {"description": "Unexpected artifact retrieval failure."},
    },
)
def get_artifact(
    conversation_id: UUID = Path(description="Conversation UUID."),
    artifact_id: UUID = Path(description="Artifact UUID to download."),
    authenticated_user: AuthenticatedUser = Depends(get_authenticated_user),
    workflow: WorkflowApp = Depends(get_workflow_app),
):
    try:
        workflow.raise_if_userid_not_relates_to_conversation_id(user_id=authenticated_user.uid, conversation_id=conversation_id)
        ref = workflow.get_artifact(
            user_id=authenticated_user.uid,
            conversation_id=conversation_id,
            artifact_id=artifact_id,
        )
    except ConversationNotFoundError:
        raise HTTPException(status_code=404, detail="conversation not found")
    except FileNotFoundError:
        raise HTTPException(status_code=404, detail="artifact not found")
    except Exception as e:
        log.exception("artifact download failed")
        raise HTTPException(status_code=500, detail=str(e))

    return Response(
        content=ref.content,
        media_type=ref.mime,
        headers={
            "Content-Disposition": "inline",
            "Cache-Control": "private, max-age=60",
        },
    )


@app.post(
    "/v1/conversations/{conversation_id}/datasets",
    response_model=UploadDatasetResponse,
    tags=["datasets"],
    summary="Upload a CSV dataset",
    description="Uploads a CSV file for the authenticated user's conversation.",
    response_description="Dataset stored successfully.",
    responses={
        400: {"description": "Invalid CSV content or empty upload."},
        401: {"description": "Missing or invalid Bearer token."},
        409: {"description": "Dataset already exists and overwrite is disabled."},
        500: {"description": "Unexpected dataset upload failure."},
    },
)
async def upload_dataset_csv(
    conversation_id: UUID = Path(description="Conversation UUID."),
    file: UploadFile = File(..., description="CSV file to upload for this conversation."),
    authenticated_user: AuthenticatedUser = Depends(get_authenticated_user),
    workflow: WorkflowApp = Depends(get_workflow_app),
):
    file_name = (file.filename or "").strip()
    content_type = (file.content_type or "").lower()
    is_csv_name = file_name.lower().endswith(".csv")
    is_csv_type = "csv" in content_type or content_type == "application/vnd.ms-excel"

    if not is_csv_name and not is_csv_type:
        raise HTTPException(status_code=400, detail="Only CSV uploads are supported.")

    csv_bytes = await file.read()
    if not csv_bytes:
        raise HTTPException(status_code=400, detail="Uploaded file is empty.")

    try:
        workflow.raise_if_userid_not_relates_to_conversation_id(user_id=authenticated_user.uid, conversation_id=conversation_id)
        dataset_id = await asyncio.to_thread(
            workflow.upload_csv_data,
            user_id=authenticated_user.uid,
            conversation_id=conversation_id,
            csv_bytes=csv_bytes,
        )
    except ConversationNotFoundError:
        raise HTTPException(status_code=404, detail="conversation not found")
    except FileExistsError as e:
        raise HTTPException(status_code=409, detail=str(e))
    except ValueError as e:
        raise HTTPException(status_code=400, detail=str(e))
    except Exception as e:
        log.exception("dataset upload failed")
        raise HTTPException(status_code=500, detail=str(e))

    return UploadDatasetResponse(
        user_id=authenticated_user.uid,
        conversation_id=conversation_id,
        dataset_id=dataset_id,
    )
    
@app.post(
    "/v1/conversations",
    response_model=CreateConversationResponse,
    tags=["conversations"],
    summary="Create a conversation",
    description="Creates a new workflow conversation for the authenticated user.",
    response_description="Created conversation identifiers.",
    responses={
        401: {"description": "Missing or invalid Bearer token."},
        500: {"description": "Unexpected conversation creation failure."},
    },
)
def create_conversation(
    authenticated_user: AuthenticatedUser = Depends(get_authenticated_user),
    workflow: WorkflowApp = Depends(get_workflow_app),
):
    user_id = authenticated_user.uid
    conversation_id = workflow.create_conversation(user_id=user_id)
    return CreateConversationResponse(user_id=user_id, conversation_id=conversation_id)


@app.post(
    "/v1/conversations/{conversation_id}/invoke",
    response_model=InvokeResponse,
    tags=["conversations"],
    summary="Invoke the workflow",
    description="Advances the authenticated user's conversation by one workflow step.",
    response_description="Workflow node response for the current step.",
    responses={
        401: {"description": "Missing or invalid Bearer token."},
        422: {"description": "Request body validation failed."},
        500: {"description": "Unexpected workflow execution failure."},
    },
)
async def invoke_once(
    req: InvokeRequest,
    conversation_id: UUID = Path(description="Conversation UUID."),
    authenticated_user: AuthenticatedUser = Depends(get_authenticated_user),
    workflow: WorkflowApp = Depends(get_workflow_app),
):
    # single node execution per request
    txt = (req.user_text or "").strip() or None

    try:
        workflow.raise_if_userid_not_relates_to_conversation_id(user_id=authenticated_user.uid, conversation_id=conversation_id)
        resp = await asyncio.to_thread(
            workflow.handle,
            WorkflowRequest(
                user_id=authenticated_user.uid,
                conversation_id=conversation_id,
                user_message=txt,
            ),
        )
    except ConversationNotFoundError:
        raise HTTPException(status_code=404, detail="conversation not found")    
    except Exception as e:
        log.exception("invoke failed")
        raise HTTPException(status_code=500, detail=str(e))

    return InvokeResponse(
        conversation_id=conversation_id,
        user_id=authenticated_user.uid,
        node_message=resp.node_message,
        needs_input=resp.needs_input,
        needs_data=resp.needs_data,
        current_stage=str(resp.current_stage),
        artifact_ids =resp.artifact_ids,
        current_stage_status=str(resp.current_stage_status),
    )
