from __future__ import annotations

OPENAPI_TAGS = [
    {"name": "system", "description": "Health and service status endpoints."},
    {
        "name": "conversations",
        "description": "Create and advance authenticated workflow conversations.",
    },
    {"name": "datasets", "description": "Upload CSV datasets for a conversation."},
    {"name": "artifacts", "description": "Download artifacts generated by the workflow."},
]

API_TITLE = "AitiaMed Copilot API"
API_VERSION = "0.1.0"
API_SUMMARY = "Authenticated API for medical causal inference workflow interactions."
API_DESCRIPTION = (
    "Upload a CSV dataset, invoke the causal workflow, and download generated artifacts.\n\n"
    "Authentication:\n"
    "- All `/v1/...` endpoints require a Firebase Bearer token.\n"
    "- `/healthz` is public.\n"
    "- The authenticated Firebase identity is mapped to the internal workflow `user_id`."
)
