from __future__ import annotations

from collections.abc import Sequence
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field


class CreateConversationResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        json_schema_extra={
            "example": {
                "user_id": "11111111-1111-1111-1111-111111111111",
                "conversation_id": "22222222-2222-2222-2222-222222222222",
            }
        },
    )

    user_id: UUID = Field(description="Authenticated internal user UUID derived from the Firebase token.")
    conversation_id: UUID = Field(description="Newly created conversation UUID.")


class UploadDatasetResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        json_schema_extra={
            "example": {
                "user_id": "11111111-1111-1111-1111-111111111111",
                "conversation_id": "22222222-2222-2222-2222-222222222222",
                "dataset_id": "33333333-3333-3333-3333-333333333333",
            }
        },
    )

    user_id: UUID = Field(description="Authenticated internal user UUID derived from the Firebase token.")
    conversation_id: UUID = Field(description="Conversation UUID that owns the dataset.")
    dataset_id: UUID = Field(description="Stored dataset UUID.")


class InvokeRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        json_schema_extra={
            "example": {
                "user_text": "Please summarize the uploaded dataset and tell me what I should check first.",
            }
        },
    )

    user_text: str | None = Field(
        default=None,
        description="User message forwarded to the current workflow stage.",
    )

class RevertStateRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        json_schema_extra={
            "example": {
                "state_name": "LOAD_DATASET",
            }
        },
    )

    state_name: str | None = Field(
        default=None,
        description="State name to revert to.",
    )
    


class InvokeResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        json_schema_extra={
            "example": {
                "conversation_id": "22222222-2222-2222-2222-222222222222",
                "user_id": "11111111-1111-1111-1111-111111111111",
                "node_message": "I loaded your dataset and summarized the main columns.",
                "needs_input": False,
                "needs_data": False,
                "artifact_ids": ["44444444-4444-4444-4444-444444444444"],
                "current_stage": "LOAD_DATASET",
                "current_stage_status": "DONE",
            }
        },
    )

    conversation_id: UUID = Field(description="Conversation UUID.")
    user_id: UUID = Field(description="Authenticated internal user UUID derived from the Firebase token.")
    node_message: str | None = Field(description="Assistant-visible message returned by the current workflow node.")
    needs_input: bool = Field(description="Whether the workflow is waiting for the user's next message.")
    needs_data: bool = Field(description="Whether the workflow is blocked until the user uploads data.")
    artifact_ids: Sequence[str] | None = Field(
        default=None,
        description="Optional artifact UUIDs generated by the workflow step.",
    )
    current_stage: str = Field(description="Current workflow stage name.")
    current_stage_status: str = Field(description="Current workflow stage status.")
