"""
This type stub file was generated by pyright.
"""

from ._criterion import LinearMomentGRFCriterion, LinearMomentGRFCriterionMSE
from .classes import CausalForest, CausalIVForest, MultiOutputGRF, RegressionForest

"""
An efficient Cython implementation of Generalized Random Forests [grf]_ and special case python classes.

References
----------
.. [grf] Athey, Susan, Julie Tibshirani, and Stefan Wager. "Generalized random forests."
    The Annals of Statistics 47.2 (2019): 1148-1178
    https://arxiv.org/pdf/1610.01271.pdf
"""
__all__ = ["CausalForest", "CausalIVForest", "RegressionForest", "MultiOutputGRF", "LinearMomentGRFCriterion", "LinearMomentGRFCriterionMSE"]
