"""
This type stub file was generated by pyright.
"""

from abc import ABCMeta
from .._ensemble import BaseEnsemble

__all__ = ["BaseGRF"]
MAX_INT = ...
class BaseGRF(BaseEnsemble, metaclass=ABCMeta):
    """
    Base class for Genearlized Random Forests.

    Solves a linear moment equations of the form::

        E[J * theta(x) - A | X = x] = 0

    where J is an (d, d) random matrix, A is an (d, 1) random vector and theta(x)
    is a local parameter to be estimated, which might contain both relevant and
    nuisance parameters.

    Warning: This class should not be used directly. Use derived classes
    instead.
    """
    def __init__(self, n_estimators=..., *, criterion=..., max_depth=..., min_samples_split=..., min_samples_leaf=..., min_weight_fraction_leaf=..., min_var_fraction_leaf=..., min_var_leaf_on_val=..., max_features=..., min_impurity_decrease=..., max_samples=..., min_balancedness_tol=..., honest=..., inference=..., fit_intercept=..., subforest_size=..., n_jobs=..., random_state=..., verbose=..., warm_start=...) -> None:
        ...
    
    def apply(self, X): # -> NDArray[Any]:
        """
        Apply trees in the forest to X, return leaf indices.

        Parameters
        ----------
        X : array_like of shape (n_samples, n_features)
            The input samples. Internally, it will be converted to
            ``dtype=np.float64``.

        Returns
        -------
        X_leaves : ndarray of shape (n_samples, n_estimators)
            For each datapoint x in X and for each tree in the forest,
            return the index of the leaf x ends up in.
        """
        ...
    
    def decision_path(self, X): # -> tuple[Any | csr_matrix | csr_array, NDArray[Any]]:
        """
        Return the decision path in the forest.

        Parameters
        ----------
        X : array_like of shape (n_samples, n_features)
            The input samples. Internally, it will be converted to
            ``dtype=np.float64``.

        Returns
        -------
        indicator : sparse matrix of shape (n_samples, n_nodes)
            Return a node indicator matrix where non zero elements indicates
            that the samples goes through the nodes. The matrix is of CSR
            format.
        n_nodes_ptr : ndarray of shape (n_estimators + 1,)
            The columns from indicator[n_nodes_ptr[i]:n_nodes_ptr[i+1]]
            gives the indicator value for the i-th estimator.
        """
        ...
    
    def fit(self, X, T, y, *, sample_weight=..., **kwargs):
        """
        Build a forest of trees from the training set (X, T, y) and any other auxiliary variables.

        Parameters
        ----------
        X : array_like of shape (n_samples, n_features)
            The training input samples. Internally, its dtype will be converted
            to ``dtype=np.float64``.
        T : array_like of shape (n_samples, n_treatments)
            The treatment vector for each sample
        y : array_like of shape (n_samples,) or (n_samples, n_outcomes)
            The outcome values for each sample.
        sample_weight : array_like of shape (n_samples,), default None
            Sample weights. If None, then samples are equally weighted. Splits
            that would create child nodes with net zero or negative weight are
            ignored while searching for a split in each node.
        **kwargs : dictionary of array_like items of shape (n_samples, d_var)
            Auxiliary random variables that go into the moment function (e.g. instrument, censoring etc)
            Any of these variables will be passed on as is to the `get_pointJ` and
            `get_alpha` method of the children classes.

        Returns
        -------
        self : object
        """
        ...
    
    def get_subsample_inds(self): # -> list[Any]:
        """Re-generate the example same sample indices as those at fit time using same pseudo-randomness."""
        ...
    
    def feature_importances(self, max_depth=..., depth_decay_exponent=...): # -> _Array1D[float64]:
        """
        Get feature importances based on the amount of parameter heterogeneity they create.

        The higher, the more important the feature.
        The importance of a feature is computed as the (normalized) total heterogeneity that the feature
        creates. For each tree and for each split that the feature was chosen adds::

            parent_weight * (left_weight * right_weight)
                * mean((value_left[k] - value_right[k])**2) / parent_weight**2

        to the importance of the feature. Each such quantity is also weighted by the depth of the split.
        These importances are normalized at the tree level and then averaged across trees.

        Parameters
        ----------
        max_depth : int, default 4
            Splits of depth larger than `max_depth` are not used in this calculation
        depth_decay_exponent: double, default 2.0
            The contribution of each split to the total score is re-weighted by 1 / (1 + `depth`)**2.0.

        Returns
        -------
        feature_importances_ : ndarray of shape (n_features,)
            Normalized total parameter heterogeneity inducing importance of each feature
        """
        ...
    
    @property
    def feature_importances_(self): # -> _Array1D[float64]:
        ...
    
    def predict_tree_average_full(self, X): # -> ndarray[tuple[int, int], dtype[float64]]:
        """
        Return the fitted local parameters for each X, i.e. theta(X).

        This method simply returns the average of the parameters estimated by each tree. `predict_full`
        should be preferred over `pred_tree_average_full`, as it performs a more stable averaging across
        trees.

        Parameters
        ----------
        X : array_like of shape (n_samples, n_features)
            The input samples. Internally, it will be converted to
            ``dtype=np.float64``.

        Returns
        -------
        theta(X) : array_like of shape (n_samples, n_outputs)
            The estimated relevant parameters for each row of X
        """
        ...
    
    def predict_tree_average(self, X): # -> ndarray[tuple[int, int], dtype[float64]] | ndarray[_AnyShape, dtype[float64]]:
        """
        Return the prefix of relevant fitted local parameters for each X, i.e. theta(X)[1..n_relevant_outputs].

        This method simply returns the average of the parameters estimated by each tree. `predict`
        should be preferred over `pred_tree_average`, as it performs a more stable averaging across
        trees.

        Parameters
        ----------
        X : array_like of shape (n_samples, n_features)
            The input samples. Internally, it will be converted to
            ``dtype=np.float64``.

        Returns
        -------
        theta(X)[1, .., n_relevant_outputs] : array_like of shape (n_samples, n_relevant_outputs)
            The estimated relevant parameters for each row of X
        """
        ...
    
    def predict_moment_and_var(self, X, parameter, slice=..., parallel=...): # -> tuple[ndarray[tuple[int, int], dtype[float64]], ndarray[tuple[int, int, int], dtype[float64]]]:
        """
        Return the value of the conditional expected moment vector and variance at each sample.

        For the given parameter estimate for each sample::

            M(x; theta(x)) := E[J | X=x] theta(x) - E[A | X=x]

        where conditional expectations are estimated based on the forest weights, i.e.::

            M_tree(x; theta(x)) := (1/ |leaf(x)|) sum_{val sample i in leaf(x)} w[i] (J[i] theta(x) - A[i])
            M(x; theta(x) = (1/n_trees) sum_{trees} M_tree(x; theta(x))

        where w[i] is the sample weight (1.0 if sample_weight is None), as well as the variance of the local
        moment vector across trees::

            Var(M_tree(x; theta(x))) = (1/n_trees) sum_{trees} M_tree(x; theta(x)) @ M_tree(x; theta(x)).T

        Parameters
        ----------
        X : array_like of shape (n_samples, n_features)
            The input samples. Internally, it will be converted to
            ``dtype=np.float64``.
        parameter : array_like of shape (n_samples, n_outputs)
            An estimate of the parameter theta(x) for each sample x in X
        slice : list of int or None, default None
            If not None, then only the trees with index in slice, will be used to calculate the mean
            and the variance.
        parallel : bool , default True
            Whether the averaging should happen using parallelism or not. Parallelism adds some overhead
            but makes it faster with many trees.

        Returns
        -------
        moment : array_like of shape (n_samples, n_outputs)
            The estimated conditional moment M(x; theta(x)) for each sample x in X
        moment_var : array_like of shape (n_samples, n_outputs)
            The variance of the conditional moment Var(M_tree(x; theta(x))) across trees for each sample x
        """
        ...
    
    def predict_alpha_and_jac(self, X, slice=..., parallel=...): # -> tuple[ndarray[tuple[int, int], dtype[float64]], ndarray[tuple[int, int, int], dtype[float64]]]:
        """
        Get the predicted alpha and jacobian values.

        The value of the conditional jacobian E[J | X=x] and the conditional alpha E[A | X=x]
        use the forest as kernel weights, i.e.::

            alpha(x) = (1/n_trees) sum_{trees} (1/ |leaf(x)|) sum_{val sample i in leaf(x)} w[i] A[i]
            jac(x) = (1/n_trees) sum_{trees} (1/ |leaf(x)|) sum_{val sample i in leaf(x)} w[i] J[i]

        where w[i] is the sample weight (1.0 if sample_weight is None).

        Parameters
        ----------
        X : array_like of shape (n_samples, n_features)
            The input samples. Internally, it will be converted to
            ``dtype=np.float64``.
        slice : list of int or None, default None
            If not None, then only the trees with index in slice, will be used to calculate the mean
            and the variance.
        parallel : bool , default True
            Whether the averaging should happen using parallelism or not. Parallelism adds some overhead
            but makes it faster with many trees.

        Returns
        -------
        alpha : array_like of shape (n_samples, n_outputs)
            The estimated conditional A, alpha(x) for each sample x in X
        jac : array_like of shape (n_samples, n_outputs, n_outputs)
            The estimated conditional J, jac(x) for each sample x in X
        """
        ...
    
    def predict_full(self, X, interval=..., alpha=...): # -> tuple[Any, _Array1D[float64], _Array1D[float64]] | tuple[Any, Any | NDArray[Any]] | Any | NDArray[Any] | tuple[Any, Any]:
        """Return the fitted local parameters for each x in X, i.e. theta(x).

        Parameters
        ----------
        X : array_like of shape (n_samples, n_features)
            The input samples. Internally, it will be converted to
            ``dtype=np.float64``.
        interval : bool, default False
            Whether to return a confidence interval too
        alpha : float in (0, 1), default 0.05
            The confidence level of the confidence interval. Returns a symmetric (alpha/2, 1-alpha/2)
            confidence interval.

        Returns
        -------
        theta(x) : array_like of shape (n_samples, n_outputs)
            The estimated relevant parameters for each row x of X
        lb(x), ub(x) : array_like of shape (n_samples, n_outputs)
            The lower and upper end of the confidence interval for each parameter. Return value is omitted if
            `interval=False`.
        """
        ...
    
    def predict(self, X, interval=..., alpha=...): # -> tuple[Any, _Array1D[float64] | Any | NDArray[Any], _Array1D[float64] | Any] | tuple[Any, ndarray[_AnyShape, dtype[float64]] | Any | ndarray[_AnyShape, dtype[Any]], ndarray[_AnyShape, dtype[float64]] | Any] | tuple[Any, _Array1D[float64], _Array1D[float64]] | tuple[Any, Any | NDArray[Any]] | Any | NDArray[Any] | tuple[Any, Any]:
        """
        Return the prefix of relevant fitted local parameters for each x in X, i.e. theta(x)[1..n_relevant_outputs].

        Parameters
        ----------
        X : array_like of shape (n_samples, n_features)
            The input samples. Internally, it will be converted to
            ``dtype=np.float64``.
        interval : bool, default False
            Whether to return a confidence interval too
        alpha : float in (0, 1), default 0.05
            The confidence level of the confidence interval. Returns a symmetric (alpha/2, 1-alpha/2)
            confidence interval.

        Returns
        -------
        theta(X)[1, .., n_relevant_outputs] : array_like of shape (n_samples, n_relevant_outputs)
            The estimated relevant parameters for each row of X
        lb(x), ub(x) : array_like of shape (n_samples, n_relevant_outputs)
            The lower and upper end of the confidence interval for each parameter. Return value is omitted if
            `interval=False`.
        """
        ...
    
    def predict_interval(self, X, alpha=...): # -> tuple[_Array1D[float64] | Any | NDArray[Any] | ndarray[_AnyShape, dtype[float64]], _Array1D[float64] | Any | ndarray[_AnyShape, dtype[float64]]]:
        """
        Return the confidence interval for the relevant fitted local parameters for each x in X.

        Parameters
        ----------
        X : array_like of shape (n_samples, n_features)
            The input samples. Internally, it will be converted to
            ``dtype=np.float64``.
        alpha : float in (0, 1), default 0.05
            The confidence level of the confidence interval. Returns a symmetric (alpha/2, 1-alpha/2)
            confidence interval.

        Returns
        -------
        lb(x), ub(x) : array_like of shape (n_samples, n_relevant_outputs)
            The lower and upper end of the confidence interval for each parameter. Return value is omitted if
            `interval=False`.
        """
        ...
    
    def predict_and_var(self, X): # -> tuple[Any, Any | NDArray[Any]] | Any | NDArray[Any] | tuple[Any, Any]:
        """
        Return the prefix of relevant fitted local parameters and their covariance matrix for each x in X.

        Parameters
        ----------
        X : array_like of shape (n_samples, n_features)
            The input samples. Internally, it will be converted to
            ``dtype=np.float64``.

        Returns
        -------
        theta(x)[1, .., n_relevant_outputs] : array_like of shape (n_samples, n_relevant_outputs)
            The estimated relevant parameters for each row of X
        var(theta(x)) : array_like of shape (n_samples, n_relevant_outputs, n_relevant_outputs)
            The covariance of theta(x)[1, .., n_relevant_outputs]
        """
        ...
    
    def predict_var(self, X): # -> tuple[Any, Any | NDArray[Any]] | Any | NDArray[Any] | tuple[Any, Any]:
        """
        Return the covariance matrix of the prefix of relevant fitted local parameters for each x in X.

        Parameters
        ----------
        X : array_like of shape (n_samples, n_features)
            The input samples. Internally, it will be converted to
            ``dtype=np.float64``.

        Returns
        -------
        var(theta(x)) : array_like of shape (n_samples, n_relevant_outputs, n_relevant_outputs)
            The covariance of theta(x)[1, .., n_relevant_outputs]
        """
        ...
    
    def prediction_stderr(self, X): # -> NDArray[Any]:
        """
        Return the standard deviation of each coordinate of the prefix of relevant fitted local parameters.

        Parameters
        ----------
        X : array_like of shape (n_samples, n_features)
            The input samples. Internally, it will be converted to
            ``dtype=np.float64``.

        Returns
        -------
        std(theta(x)) : array_like of shape (n_samples, n_relevant_outputs)
            The standard deviation of each theta(x)[i] for i in {1, .., n_relevant_outputs}
        """
        ...
    
    def predict_projection_and_var(self, X, projector): # -> tuple[Any, Any | NDArray[Any]] | Any | NDArray[Any] | tuple[Any, Any]:
        """
        Return the product of the prefix of relevant fitted local parameters with a projector vector, and its variance.

        That is::

            mu(x) := <theta(x)[1..n_relevant_outputs], projector(x)>

        as well as the variance of mu(x).

        Parameters
        ----------
        X : array_like of shape (n_samples, n_features)
            The input samples. Internally, it will be converted to
            ``dtype=np.float64``.
        projector : array_like of shape (n_samples, n_relevant_outputs)
            The projector vector for each sample x in X

        Returns
        -------
        mu(x) : array_like of shape (n_samples, 1)
            The estimated inner product of the relevant parameters with the projector for each row x of X
        var(mu(x)) : array_like of shape (n_samples, 1)
            The variance of the estimated inner product
        """
        ...
    
    def predict_projection(self, X, projector): # -> tuple[Any, Any | NDArray[Any]] | Any | NDArray[Any] | tuple[Any, Any]:
        """
        Return the product of the prefix of relevant fitted local parameters with a projector vector.

        That is::

            mu(x) := <theta(x)[1..n_relevant_outputs], projector(x)>

        Parameters
        ----------
        X : array_like of shape (n_samples, n_features)
            The input samples. Internally, it will be converted to
            ``dtype=np.float64``.
        projector : array_like of shape (n_samples, n_relevant_outputs)
            The projector vector for each sample x in X

        Returns
        -------
        mu(x) : array_like of shape (n_samples, 1)
            The estimated inner product of the relevant parameters with the projector for each row x of X
        """
        ...
    
    def predict_projection_var(self, X, projector): # -> tuple[Any, Any | NDArray[Any]] | Any | NDArray[Any] | tuple[Any, Any]:
        """
        Return the variance of the product of the prefix of relevant fitted local parameters with a projector vector.

        That is::

            Var(mu(x)) for mu(x) := <theta(x)[1..n_relevant_outputs], projector(x)>

        Parameters
        ----------
        X : array_like of shape (n_samples, n_features)
            The input samples. Internally, it will be converted to
            ``dtype=np.float64``.
        projector : array_like of shape (n_samples, n_relevant_outputs)
            The projector vector for each sample x in X

        Returns
        -------
        var(mu(x)) : array_like of shape (n_samples, 1)
            The variance of the estimated inner product
        """
        ...
    
    def oob_predict(self, Xtrain): # -> Any:
        """
        Return the relevant output predictions for each data point, using the trees that didn't use that data point.

        This method is not available is the estimator was trained with `warm_start=True`.

        Parameters
        ----------
        Xtrain : (n_training_samples, n_features) matrix
            Must be the same exact X matrix that was passed to the forest at fit time.

        Returns
        -------
        oob_preds : (n_training_samples, n_relevant_outputs) matrix
            The out-of-bag predictions of the relevant output parameters for each of the training points
        """
        ...
    


