"""
This type stub file was generated by pyright.
"""

import abc
from typing import List, Optional
from sklearn.base import BaseEstimator

"""Collection of scikit-learn extensions for model selection techniques."""
class WeightedKFold:
    """K-Folds cross-validator for weighted data.

    Provides train/test indices to split data in train/test sets.
    Split dataset into k folds of roughly equal size and equal total weight.

    The default is to try sklearn.model_selection.KFold a number of trials to find
    a weight-balanced k-way split. If it cannot find such a split, it will fall back
    onto a more rigorous weight stratification algorithm.

    Parameters
    ----------
    n_splits : int, default 3
        Number of folds. Must be at least 2.

    n_trials : int, default 10
        Number of times to try sklearn.model_selection.KFold before falling back to another
        weight stratification algorithm.

    shuffle : bool, optional
        Whether to shuffle the data before splitting into batches.

    random_state : int, RandomState instance, or None, default None
            If int, random_state is the seed used by the random number generator;
        If :class:`~numpy.random.mtrand.RandomState` instance, random_state is the random number generator;
        If None, the random number generator is the :class:`~numpy.random.mtrand.RandomState` instance used
        by :mod:`np.random<numpy.random>`. Used when ``shuffle`` == True.
    """
    def __init__(self, n_splits=..., n_trials=..., shuffle=..., random_state=...) -> None:
        ...
    
    def split(self, X, y, sample_weight=...): # -> Iterator[tuple[ndarray[_AnyShape, dtype[Any]], ndarray[_AnyShape, dtype[Any]]]] | Iterator[Any]:
        """Generate indices to split data into training and test set.

        Parameters
        ----------
        X : array_like, shape (n_samples, n_features)
            Training data, where n_samples is the number of samples
            and n_features is the number of features.

        y : array_like, shape (n_samples,)
            The target variable for supervised learning problems.

        sample_weight : array_like, shape (n_samples,)
            Weights associated with the training data.
        """
        ...
    
    def get_n_splits(self, X, y, groups=...): # -> int:
        """Return the number of splitting iterations in the cross-validator.

        Parameters
        ----------
        X : object
            Always ignored, exists for compatibility.

        y : object
            Always ignored, exists for compatibility.

        groups : object
            Always ignored, exists for compatibility.

        Returns
        -------
        n_splits : int
            Returns the number of splitting iterations in the cross-validator.
        """
        ...
    


class WeightedStratifiedKFold(WeightedKFold):
    """Stratified K-Folds cross-validator for weighted data.

    Provides train/test indices to split data in train/test sets.
    Split dataset into k folds of roughly equal size and equal total weight.

    The default is to try sklearn.model_selection.StratifiedKFold a number of trials to find
    a weight-balanced k-way split. If it cannot find such a split, it will fall back
    onto a more rigorous weight stratification algorithm.

    Parameters
    ----------
    n_splits : int, default 3
        Number of folds. Must be at least 2.

    n_trials : int, default 10
        Number of times to try sklearn.model_selection.StratifiedKFold before falling back to another
        weight stratification algorithm.

    shuffle : bool, optional
        Whether to shuffle the data before splitting into batches.

    random_state : int, RandomState instance, or None, default None
            If int, random_state is the seed used by the random number generator;
        If :class:`~numpy.random.mtrand.RandomState` instance, random_state is the random number generator;
        If None, the random number generator is the :class:`~numpy.random.mtrand.RandomState` instance used
        by :mod:`np.random<numpy.random>`. Used when ``shuffle`` == True.
    """
    def split(self, X, y, sample_weight=...): # -> Iterator[tuple[ndarray[_AnyShape, dtype[Any]], ndarray[_AnyShape, dtype[Any]]]] | Iterator[Any]:
        """Generate indices to split data into training and test set.

        Parameters
        ----------
        X : array_like, shape (n_samples, n_features)
            Training data, where n_samples is the number of samples
            and n_features is the number of features.

        y : array_like, shape (n_samples,)
            The target variable for supervised learning problems.

        sample_weight : array_like, shape (n_samples,)
            Weights associated with the training data.
        """
        ...
    
    def get_n_splits(self, X, y, groups=...): # -> int:
        """Return the number of splitting iterations in the cross-validator.

        Parameters
        ----------
        X : object
            Always ignored, exists for compatibility.

        y : object
            Always ignored, exists for compatibility.

        groups : object
            Always ignored, exists for compatibility.

        Returns
        -------
        n_splits : int
            Returns the number of splitting iterations in the cross-validator.
        """
        ...
    


class ModelSelector(metaclass=abc.ABCMeta):
    """
    Class that enables a two-stage fitting process.

    First a model is selected by calling `train` with `is_selecting=True`, and then the selected model is fit
    (presumably on a different data set) by calling train with `is_selecting=False`.
    """
    @abc.abstractmethod
    def train(self, is_selecting: bool, folds: Optional[List], *args, **kwargs):
        """Select a model or fit a model, depending on the value of `is_selecting`.

        If `is_selecting` is `False`, then `folds` should not be provided because they are only during selection.
        """
        ...
    
    @abc.abstractmethod
    def predict(self, *args, **kwargs):
        """
        Predict using the selected model.

        This method should not be called until after `train` has been used both to select a model and to fit it.
        """
        ...
    
    @abc.abstractmethod
    def score(self, *args, **kwargs):
        """
        Get the score of the selected model on the given data.

        This method should not be called until after `train` has been used
        both to select a model and to fit it.
        """
        ...
    


class SingleModelSelector(ModelSelector):
    """
    A model selection class that selects a single best model.

    This encompasses random search, grid search, ensembling, etc.
    """
    @property
    @abc.abstractmethod
    def best_model(self):
        ...
    
    @property
    @abc.abstractmethod
    def best_score(self):
        ...
    
    def predict(self, *args, **kwargs):
        ...
    
    def __getattr__(self, name): # -> Any | None:
        ...
    
    def score(self, *args, **kwargs): # -> None:
        ...
    


class FixedModelSelector(SingleModelSelector):
    """Model selection class that always selects the given sklearn-compatible model."""
    def __init__(self, model, score_during_selection) -> None:
        ...
    
    def train(self, is_selecting, folds: Optional[List], X, y, groups=..., **kwargs): # -> Self:
        ...
    
    @property
    def best_model(self): # -> Any:
        ...
    
    @property
    def best_score(self): # -> floating[Any]:
        ...
    


class SklearnCVSelector(SingleModelSelector):
    """Wraps one of sklearn's CV classes in the ModelSelector interface."""
    def __init__(self, searcher) -> None:
        ...
    
    @staticmethod
    def convertible_types(): # -> set[Any]:
        ...
    
    @staticmethod
    def can_wrap(model): # -> bool:
        ...
    
    def train(self, is_selecting: bool, folds: Optional[List], *args, groups=..., **kwargs): # -> Self:
        ...
    
    @property
    def best_model(self):
        ...
    
    @property
    def best_score(self):
        ...
    


class ListSelector(SingleModelSelector):
    """
    Model selection class that selects the best model from a list of model selectors.

    Parameters
    ----------
    models : list of ModelSelector
        The list of model selectors to choose from
    unwrap : bool, default True
        Whether to return the best model's best model, rather than just the outer best model selector
    """
    def __init__(self, models, unwrap=...) -> None:
        ...
    
    def train(self, is_selecting, folds: Optional[List], *args, **kwargs): # -> None:
        ...
    
    @property
    def best_model(self): # -> Any:
        """
        Get the best model.

        Note that if we were selecting over SingleModelSelectors and `unwrap` is `False`,
        we will return the SingleModelSelector instance, not its best model.
        """
        ...
    
    @property
    def best_score(self):
        ...
    


def get_selector(input, is_discrete, *, random_state=..., cv=..., wrapper=..., needs_scoring=...): # -> ModelSelector | ListSelector | SklearnCVSelector | FixedModelSelector:
    ...

class GridSearchCVList(BaseEstimator):
    """
    An extension of GridSearchCV that allows for passing a list of estimators.

    Each estimator can have its own
    parameter grid and we will return the best among all estimators in the list and hyperparameters in its
    corresponding grid. We are only changing the estimator parameter to estimator_list and the param_grid
    parameter to be a list of parameter grids. The rest of the parameters are the same as in
    :meth:`~sklearn.model_selection.GridSearchCV`. See the documentation of that class
    for explanation of the remaining parameters.

    Parameters
    ----------
    estimator_list : list of estimator object.
        Each estimator in th list is assumed to implement the scikit-learn estimator interface.
        Either estimator needs to provide a ``score`` function,
        or ``scoring`` must be passed.

    param_grid : list of dict or list of list of dictionaries
        For each estimator, the dictionary with parameters names (`str`) as keys and lists of
        parameter settings to try as values, or a list of such
        dictionaries, in which case the grids spanned by each dictionary
        in the list are explored. This enables searching over any sequence
        of parameter settings.
    """
    def __init__(self, estimator_list, param_grid_list, scoring=..., n_jobs=..., refit=..., cv=..., verbose=..., pre_dispatch=..., error_score=..., return_train_score=...) -> None:
        ...
    
    def fit(self, X, y=..., **fit_params): # -> Self:
        ...
    
    def predict(self, X):
        ...
    
    def predict_proba(self, X):
        ...
    


