"""
This type stub file was generated by pyright.
"""

import abc

class Inference(metaclass=abc.ABCMeta):
    def prefit(self, estimator, *args, **kwargs): # -> None:
        """Perform any necessary logic before the estimator's fit has been called."""
        ...
    
    @abc.abstractmethod
    def fit(self, estimator, *args, **kwargs):
        """
        Fits the inference model.

        This is called after the estimator's fit.
        """
        ...
    
    def ate_interval(self, X=..., *, T0=..., T1=..., alpha=...):
        ...
    
    def ate_inference(self, X=..., *, T0=..., T1=...):
        ...
    
    def marginal_ate_interval(self, T, X=..., *, alpha=...):
        ...
    
    def marginal_ate_inference(self, T, X=...):
        ...
    
    def const_marginal_ate_interval(self, X=..., *, alpha=...):
        ...
    
    def const_marginal_ate_inference(self, X=...):
        ...
    


class BootstrapInference(Inference):
    """
    Inference instance to perform bootstrapping.

    This class can be used for inference with any CATE estimator.

    Parameters
    ----------
    n_bootstrap_samples : int, default 100
        How many draws to perform.

    n_jobs: int, default -1
        The maximum number of concurrently running jobs, as in joblib.Parallel.

    verbose: int, default: 0
        Verbosity level

    bootstrap_type: 'percentile', 'pivot', or 'normal', default 'pivot'
        Bootstrap method used to compute results.
        'percentile' will result in using the empiracal CDF of the replicated computations of the statistics.
        'pivot' will also use the replicates but create a pivot interval that also relies on the estimate
        over the entire dataset.
        'normal' will instead compute a pivot interval assuming the replicates are normally distributed.
    """
    def __init__(self, n_bootstrap_samples=..., n_jobs=..., bootstrap_type=..., verbose=...) -> None:
        ...
    
    def fit(self, estimator, *args, **kwargs): # -> None:
        ...
    
    def __getattr__(self, name): # -> Callable[..., Any] | Any:
        ...
    


class GenericModelFinalInference(Inference):
    """
    Inference based on predict_interval of the model_final model.

    Assumes that estimator
    class has a model_final method, whose predict(cross_product(X, [0, ..., 1, ..., 0])) gives
    the const_marginal_effect of the treamtnent at the column with value 1 and which also supports
    prediction_stderr(X).
    """
    def prefit(self, estimator, *args, **kwargs): # -> None:
        ...
    
    def fit(self, estimator, *args, **kwargs): # -> None:
        ...
    
    def const_marginal_effect_interval(self, X, *, alpha=...): # -> tuple[generic[Any] | NDArray[bytes_] | NDArray[complex128] | NDArray[str_] | NDArray[Any] | Any | complex | str | bytes | memoryview[int], generic[Any] | NDArray[bytes_] | NDArray[complex128] | NDArray[str_] | NDArray[Any] | Any | complex | str | bytes | memoryview[int]]:
        ...
    
    def const_marginal_effect_inference(self, X): # -> NormalInferenceResults:
        ...
    


class GenericSingleTreatmentModelFinalInference(GenericModelFinalInference):
    """
    Inference based on predict_interval of the model_final model.

    Assumes that treatment is single dimensional.
    Thus, the predict(X) of model_final gives the const_marginal_effect(X). The single dimensionality allows us
    to implement effect_interval(X, T0, T1) based on the const_marginal_effect_interval.
    """
    def fit(self, estimator, *args, **kwargs): # -> None:
        ...
    
    def effect_interval(self, X, *, T0, T1, alpha=...): # -> tuple[generic[Any] | NDArray[bytes_] | NDArray[complex128] | NDArray[str_] | NDArray[Any] | Any | complex | str | bytes | memoryview[int], generic[Any] | NDArray[bytes_] | NDArray[complex128] | NDArray[str_] | NDArray[Any] | Any | complex | str | bytes | memoryview[int]]:
        ...
    
    def effect_inference(self, X, *, T0, T1): # -> NormalInferenceResults:
        ...
    
    def marginal_effect_inference(self, T, X): # -> NormalInferenceResults:
        ...
    
    def marginal_effect_interval(self, T, X, *, alpha=...): # -> tuple[generic[Any] | NDArray[bytes_] | NDArray[complex128] | NDArray[str_] | NDArray[Any] | Any | complex | str | bytes | memoryview[int], generic[Any] | NDArray[bytes_] | NDArray[complex128] | NDArray[str_] | NDArray[Any] | Any | complex | str | bytes | memoryview[int]]:
        ...
    


class LinearModelFinalInference(GenericModelFinalInference):
    """
    Inference based on predict_interval of the model_final model.

    Assumes that estimator
    class has a model_final method and that model is linear. Thus, the predict(cross_product(X, T1 - T0)) gives
    the effect(X, T0, T1). This allows us to implement effect_interval(X, T0, T1) based on the
    predict_interval of model_final.
    """
    def fit(self, estimator, *args, **kwargs): # -> None:
        ...
    
    def effect_interval(self, X, *, T0, T1, alpha=...): # -> tuple[generic[Any] | NDArray[bytes_] | NDArray[complex128] | NDArray[str_] | NDArray[Any] | Any | complex | str | bytes | memoryview[int], generic[Any] | NDArray[bytes_] | NDArray[complex128] | NDArray[str_] | NDArray[Any] | Any | complex | str | bytes | memoryview[int]]:
        ...
    
    def effect_inference(self, X, *, T0, T1): # -> NormalInferenceResults:
        ...
    
    def const_marginal_effect_inference(self, X): # -> NormalInferenceResults:
        ...
    
    def marginal_effect_inference(self, T, X): # -> NormalInferenceResults:
        ...
    
    def marginal_effect_interval(self, T, X, *, alpha=...): # -> tuple[generic[Any] | NDArray[bytes_] | NDArray[complex128] | NDArray[str_] | NDArray[Any] | Any | complex | str | bytes | memoryview[int], generic[Any] | NDArray[bytes_] | NDArray[complex128] | NDArray[str_] | NDArray[Any] | Any | complex | str | bytes | memoryview[int]]:
        ...
    
    def coef__interval(self, *, alpha=...): # -> tuple[Any, Any]:
        ...
    
    def coef__inference(self): # -> NormalInferenceResults:
        ...
    
    def intercept__interval(self, *, alpha=...): # -> tuple[Any | ndarray[tuple[int], dtype[Any]] | None, Any | ndarray[tuple[int], dtype[Any]] | None]:
        ...
    
    def intercept__inference(self): # -> NormalInferenceResults:
        ...
    


class StatsModelsInference(LinearModelFinalInference):
    """Stores statsmodels covariance options.

    This class can be used for inference by the LinearDML.

    Parameters
    ----------
    cov_type : str, default 'HC1'
        The type of covariance estimation method to use.  Supported values are 'nonrobust',
        'HC0', 'HC1'.
    """
    def __init__(self, cov_type=...) -> None:
        ...
    
    def prefit(self, estimator, *args, **kwargs): # -> None:
        ...
    


class GenericModelFinalInferenceDiscrete(Inference):
    """
    Inference where a separate generic model_final is used to fit the CATE associated with each treatment.

    This model_final supports predict_interval. Inference is based on predict_interval of the model_final model.
    """
    def prefit(self, estimator, *args, **kwargs): # -> None:
        ...
    
    def fit(self, estimator, *args, **kwargs): # -> None:
        ...
    
    def const_marginal_effect_interval(self, X, *, alpha=...): # -> tuple[generic[Any] | NDArray[bytes_] | NDArray[complex128] | NDArray[str_] | NDArray[Any] | Any | complex | str | bytes | memoryview[int], generic[Any] | NDArray[bytes_] | NDArray[complex128] | NDArray[str_] | NDArray[Any] | Any | complex | str | bytes | memoryview[int]]:
        ...
    
    def const_marginal_effect_inference(self, X): # -> NormalInferenceResults:
        ...
    
    def effect_interval(self, X, *, T0, T1, alpha=...): # -> tuple[generic[Any] | NDArray[bytes_] | NDArray[complex128] | NDArray[str_] | NDArray[Any] | Any | complex | str | bytes | memoryview[int], generic[Any] | NDArray[bytes_] | NDArray[complex128] | NDArray[str_] | NDArray[Any] | Any | complex | str | bytes | memoryview[int]]:
        ...
    
    def effect_inference(self, X, *, T0, T1): # -> NormalInferenceResults:
        ...
    


class LinearModelFinalInferenceDiscrete(GenericModelFinalInferenceDiscrete):
    """
    Inference method for estimators with linear-in-X final models for each categorical treatment.

    Implements the coef__interval and intercept__interval
    based on the corresponding methods of the underlying model_final estimator.
    """
    def const_marginal_effect_inference(self, X): # -> NormalInferenceResults:
        ...
    
    def effect_inference(self, X, *, T0, T1): # -> NormalInferenceResults:
        ...
    
    def coef__interval(self, T, *, alpha=...):
        ...
    
    def coef__inference(self, T): # -> NormalInferenceResults:
        ...
    
    def intercept__interval(self, T, *, alpha=...):
        ...
    
    def intercept__inference(self, T): # -> NormalInferenceResults:
        ...
    


class StatsModelsInferenceDiscrete(LinearModelFinalInferenceDiscrete):
    """
    Special case where final model is a StatsModelsLinearRegression.

    Parameters
    ----------
    cov_type : str, default 'HC1'
        The type of covariance estimation method to use.  Supported values are 'nonrobust',
        'HC0', 'HC1'.
    """
    def __init__(self, cov_type=...) -> None:
        ...
    
    def prefit(self, estimator, *args, **kwargs): # -> None:
        ...
    


class InferenceResults(metaclass=abc.ABCMeta):
    """
    Results class for inferences.

    Parameters
    ----------
    d_t: int or None
        Number of treatments
    d_y: int
        Number of outputs
    pred : array_like, shape (m, d_y, d_t) or (m, d_y)
        The prediction of the metric for each sample X[i].
        Note that when Y or T is a vector rather than a 2-dimensional array,
        the corresponding singleton dimensions should be collapsed
        (e.g. if both are vectors, then the input of this argument will also be a vector)
    inf_type: str
        The type of inference result.
        It could be either 'effect', 'coefficient' or 'intercept'.
    fname_transformer: None or predefined function
        The transform function to get the corresponding feature names from featurizer
    """
    def __init__(self, d_t, d_y, pred, inf_type, fname_transformer=..., feature_names=..., output_names=..., treatment_names=...) -> None:
        ...
    
    @property
    def point_estimate(self): # -> NDArray[Any] | generic[Any] | complex | str | bytes | memoryview[int] | Any | NDArray[complex128] | NDArray[str_] | NDArray[bytes_]:
        """
        Get the point estimate of each treatment on each outcome for each sample X[i].

        Returns
        -------
        prediction : array_like, shape (m, d_y, d_t) or (m, d_y)
            The point estimate of each treatment on each outcome for each sample X[i].
            Note that when Y or T is a vector rather than a 2-dimensional array,
            the corresponding singleton dimensions in the output will be collapsed
            (e.g. if both are vectors, then the output of this method will also be a vector)
        """
        ...
    
    @property
    @abc.abstractmethod
    def stderr(self):
        """
        Get the standard error of the metric of each treatment on each outcome for each sample X[i].

        Returns
        -------
        stderr : array_like, shape (m, d_y, d_t) or (m, d_y)
            The standard error of the metric of each treatment on each outcome for each sample X[i].
            Note that when Y or T is a vector rather than a 2-dimensional array,
            the corresponding singleton dimensions in the output will be collapsed
            (e.g. if both are vectors, then the output of this method will also be a vector)
        """
        ...
    
    @property
    def var(self): # -> None:
        """
        Get the variance of the metric of each treatment on each outcome for each sample X[i].

        Returns
        -------
        var : array_like, shape (m, d_y, d_t) or (m, d_y)
            The variance of the metric of each treatment on each outcome for each sample X[i].
            Note that when Y or T is a vector rather than a 2-dimensional array,
            the corresponding singleton dimensions in the output will be collapsed
            (e.g. if both are vectors, then the output of this method will also be a vector)
        """
        ...
    
    @abc.abstractmethod
    def conf_int(self, alpha=...):
        """
        Get the confidence interval of the metric of each treatment on each outcome for each sample X[i].

        Parameters
        ----------
        alpha:  float in [0, 1], default 0.05
            The overall level of confidence of the reported interval.
            The alpha/2, 1-alpha/2 confidence interval is reported.

        Returns
        -------
        lower, upper: tuple of array, shape (m, d_y, d_t) or (m, d_y)
            The lower and the upper bounds of the confidence interval for each quantity.
            Note that when Y or T is a vector rather than a 2-dimensional array,
            the corresponding singleton dimensions in the output will be collapsed
            (e.g. if both are vectors, then the output of this method will also be a vector)
        """
        ...
    
    @abc.abstractmethod
    def pvalue(self, value=...):
        """
        Get the p value of the z test of each treatment on each outcome for each sample X[i].

        Parameters
        ----------
        value: float, default 0
            The mean value of the metric you'd like to test under null hypothesis.

        Returns
        -------
        pvalue : array_like, shape (m, d_y, d_t) or (m, d_y)
            The p value of the z test of each treatment on each outcome for each sample X[i].
            Note that when Y or T is a vector rather than a 2-dimensional array,
            the corresponding singleton dimensions in the output will be collapsed
            (e.g. if both are vectors, then the output of this method will also be a vector)
        """
        ...
    
    def zstat(self, value=...):
        """
        Get the z statistic of the metric of each treatment on each outcome for each sample X[i].

        Parameters
        ----------
        value: float, default 0
            The mean value of the metric you'd like to test under null hypothesis.

        Returns
        -------
        zstat : array_like, shape (m, d_y, d_t) or (m, d_y)
            The z statistic of the metric of each treatment on each outcome for each sample X[i].
            Note that when Y or T is a vector rather than a 2-dimensional array,
            the corresponding singleton dimensions in the output will be collapsed
            (e.g. if both are vectors, then the output of this method will also be a vector)
        """
        ...
    
    def summary_frame(self, alpha=..., value=..., decimals=..., feature_names=..., output_names=..., treatment_names=...): # -> DataFrame:
        """
        Output the dataframe for all the inferences above.

        Parameters
        ----------
        alpha:  float in [0, 1], default 0.05
            The overall level of confidence of the reported interval.
            The alpha/2, 1-alpha/2 confidence interval is reported.
        value: float, default 0
            The mean value of the metric you'd like to test under null hypothesis.
        decimals: int, default 3
            Number of decimal places to round each column to.
        feature_names: list of str, optional
            The names of the features X
        output_names: list of str, optional
            The names of the outputs
        treatment_names: list of str, optional
            The names of the treatments

        Returns
        -------
        output: DataFrame
            The output dataframe includes point estimate, standard error, z score, p value and confidence intervals
            of the estimated metric of each treatment on each outcome for each sample X[i]
        """
        ...
    
    def population_summary(self, alpha=..., value=..., decimals=..., tol=..., output_names=..., treatment_names=...): # -> PopulationSummaryResults:
        """
        Output the object of population summary results.

        Parameters
        ----------
        alpha:  float in [0, 1], default 0.05
            The overall level of confidence of the reported interval.
            The alpha/2, 1-alpha/2 confidence interval is reported.
        value: float, default 0
            The mean value of the metric you'd like to test under null hypothesis.
        decimals: int, default 3
            Number of decimal places to round each column to.
        tol:  float, default 0.001
            The stopping criterion. The iterations will stop when the outcome is less than ``tol``
        output_names: list of str, optional
            The names of the outputs
        treatment_names: list of str, optional
            The names of the treatments

        Returns
        -------
        PopulationSummaryResults: object
            The population summary results instance contains the different summary analysis of point estimate
            for sample X on each treatment and outcome.
        """
        ...
    
    def translate(self, offset): # -> None:
        """
        Update the results in place by translating by an offset.

        Parameters
        ----------
        offset: array_like
            The offset by which to translate these results
        """
        ...
    
    @abc.abstractmethod
    def scale(self, factor): # -> None:
        """
        Update the results in place by scaling by a factor.

        Parameters
        ----------
        factor: array_like
            The factor by which to scale these results
        """
        ...
    


class NormalInferenceResults(InferenceResults):
    """
    Results class for inference assuming a normal distribution.

    Parameters
    ----------
    d_t: int or None
        Number of treatments
    d_y: int
        Number of outputs
    pred : array_like, shape (m, d_y, d_t) or (m, d_y)
        The prediction of the metric for each sample X[i].
        Note that when Y or T is a vector rather than a 2-dimensional array,
        the corresponding singleton dimensions should be collapsed
        (e.g. if both are vectors, then the input of this argument will also be a vector)
    pred_stderr : array_like, shape (m, d_y, d_t) or (m, d_y)
        The prediction standard error of the metric for each sample X[i].
        Note that when Y or T is a vector rather than a 2-dimensional array,
        the corresponding singleton dimensions should be collapsed
        (e.g. if both are vectors, then the input of this argument will also be a vector)
    mean_pred_stderr: None or array_like or scaler, shape (d_y, d_t) or (d_y,)
        The standard error of the mean point estimate, this is derived from coefficient stderr when final
        stage is linear model, otherwise it's None.
        This is the exact standard error of the mean, which is not conservative.
    inf_type: str
        The type of inference result.
        It could be either 'effect', 'coefficient' or 'intercept'.
    fname_transformer: None or predefined function
        The transform function to get the corresponding feature names from featurizer
    """
    def __init__(self, d_t, d_y, pred, pred_stderr, mean_pred_stderr, inf_type, fname_transformer=..., feature_names=..., output_names=..., treatment_names=...) -> None:
        ...
    
    @property
    def stderr(self): # -> NDArray[Any] | generic[Any] | complex | str | bytes | memoryview[int] | Any | NDArray[complex128]:
        """
        Get the standard error of the metric of each treatment on each outcome for each sample X[i].

        Returns
        -------
        stderr : array_like, shape (m, d_y, d_t) or (m, d_y)
            The standard error of the metric of each treatment on each outcome for each sample X[i].
            Note that when Y or T is a vector rather than a 2-dimensional array,
            the corresponding singleton dimensions in the output will be collapsed
            (e.g. if both are vectors, then the output of this method will also be a vector)
        """
        ...
    
    def conf_int(self, alpha=...): # -> tuple[generic[Any] | NDArray[bytes_] | NDArray[complex128] | NDArray[str_] | NDArray[Any] | Any | complex | str | bytes | memoryview[int], generic[Any] | NDArray[bytes_] | NDArray[complex128] | NDArray[str_] | NDArray[Any] | Any | complex | str | bytes | memoryview[int]]:
        """
        Get the confidence interval of the metric of each treatment on each outcome for each sample X[i].

        Parameters
        ----------
        alpha:  float in [0, 1], default 0.05
            The overall level of confidence of the reported interval.
            The alpha/2, 1-alpha/2 confidence interval is reported.

        Returns
        -------
        lower, upper: tuple of array, shape (m, d_y, d_t) or (m, d_y)
            The lower and the upper bounds of the confidence interval for each quantity.
            Note that when Y or T is a vector rather than a 2-dimensional array,
            the corresponding singleton dimensions in the output will be collapsed
            (e.g. if both are vectors, then the output of this method will also be a vector)
        """
        ...
    
    def pvalue(self, value=...): # -> ndarray[_AnyShape, dtype[Any]] | ndarray[tuple[()], dtype[Any]]:
        """
        Get the p value of the z test of each treatment on each outcome for each sample X[i].

        Parameters
        ----------
        value: float, default 0
            The mean value of the metric you'd like to test under null hypothesis.

        Returns
        -------
        pvalue : array_like, shape (m, d_y, d_t) or (m, d_y)
            The p value of the z test of each treatment on each outcome for each sample X[i].
            Note that when Y or T is a vector rather than a 2-dimensional array,
            the corresponding singleton dimensions in the output will be collapsed
            (e.g. if both are vectors, then the output of this method will also be a vector)
        """
        ...
    
    def population_summary(self, alpha=..., value=..., decimals=..., tol=..., output_names=..., treatment_names=...): # -> PopulationSummaryResults:
        ...
    
    def scale(self, factor): # -> None:
        ...
    


class EmpiricalInferenceResults(InferenceResults):
    """
    Results class for inference with an empirical set of samples.

    Parameters
    ----------
    pred : array_like, shape (m, d_y, d_t) or (m, d_y)
        the point estimates of the metric using the full sample
    pred_dist : array_like, shape (b, m, d_y, d_t) or (b, m, d_y)
        the raw predictions of the metric sampled b times.
        Note that when Y or T is a vector rather than a 2-dimensional array,
        the corresponding singleton dimensions should be collapsed
    d_t: int or None
        Number of treatments
    d_y: int
        Number of outputs
    inf_type: str
        The type of inference result.
        It could be either 'effect', 'coefficient' or 'intercept'.
    fname_transformer: None or predefined function
        The transform function to get the corresponding feature names from featurizer
    """
    def __init__(self, d_t, d_y, pred, pred_dist, inf_type, fname_transformer=..., feature_names=..., output_names=..., treatment_names=...) -> None:
        ...
    
    @property
    def stderr(self):
        """
        Get the standard error of the metric of each treatment on each outcome for each sample X[i].

        Returns
        -------
        stderr : array_like, shape (m, d_y, d_t) or (m, d_y)
            The standard error of the metric of each treatment on each outcome for each sample X[i].
            Note that when Y or T is a vector rather than a 2-dimensional array,
            the corresponding singleton dimensions in the output will be collapsed
            (e.g. if both are vectors, then the output of this method will also be a vector)
        """
        ...
    
    def conf_int(self, alpha=...): # -> tuple[Any, Any]:
        """
        Get the confidence interval of the metric of each treatment on each outcome for each sample X[i].

        Parameters
        ----------
        alpha:  float in [0, 1], default 0.05
            The overall level of confidence of the reported interval.
            The alpha/2, 1-alpha/2 confidence interval is reported.

        Returns
        -------
        lower, upper: tuple of array, shape (m, d_y, d_t) or (m, d_y)
            The lower and the upper bounds of the confidence interval for each quantity.
            Note that when Y or T is a vector rather than a 2-dimensional array,
            the corresponding singleton dimensions in the output will be collapsed
            (e.g. if both are vectors, then the output of this method will also be a vector)
        """
        ...
    
    def pvalue(self, value=...): # -> NDArray[Any]:
        """
        Get the p value of the each treatment on each outcome for each sample X[i].

        Parameters
        ----------
        value: float, default 0
            The mean value of the metric you'd like to test under null hypothesis.

        Returns
        -------
        pvalue : array_like, shape (m, d_y, d_t) or (m, d_y)
            The p value of of each treatment on each outcome for each sample X[i].
            Note that when Y or T is a vector rather than a 2-dimensional array,
            the corresponding singleton dimensions in the output will be collapsed
            (e.g. if both are vectors, then the output of this method will also be a vector)
        """
        ...
    
    def translate(self, other): # -> None:
        ...
    
    def scale(self, factor): # -> None:
        ...
    


class PopulationSummaryResults:
    """
    Population summary results class for inferences.

    Parameters
    ----------
    d_t: int or None
        Number of treatments
    d_y: int
        Number of outputs
    pred : array_like, shape (m, d_y, d_t) or (m, d_y)
        The prediction of the metric for each sample X[i].
        Note that when Y or T is a vector rather than a 2-dimensional array,
        the corresponding singleton dimensions should be collapsed
        (e.g. if both are vectors, then the input of this argument will also be a vector)
    pred_stderr : array_like, shape (m, d_y, d_t) or (m, d_y)
        The prediction standard error of the metric for each sample X[i].
        Note that when Y or T is a vector rather than a 2-dimensional array,
        the corresponding singleton dimensions should be collapsed
        (e.g. if both are vectors, then the input of this argument will also be a vector)
    mean_pred_stderr: None or array_like or scalar, shape (d_y, d_t) or (d_y,)
        The standard error of the mean point estimate, this is derived from coefficient stderr when final
        stage is linear model, otherwise it's None.
        This is the exact standard error of the mean, which is not conservative.
    alpha: ffloat in [0, 1], default 0.05
        The overall level of confidence of the reported interval.
        The alpha/2, 1-alpha/2 confidence interval is reported.
    value: float, default 0
        The mean value of the metric you'd like to test under null hypothesis.
    decimals: int, default 3
        Number of decimal places to round each column to.
    tol: float, default 0.001
        The stopping criterion. The iterations will stop when the outcome is less than ``tol``
    output_names: list of str, optional
            The names of the outputs
    treatment_names: list of str, optional
        The names of the treatments

    """
    def __init__(self, pred, pred_stderr, mean_pred_stderr, d_t, d_y, alpha=..., value=..., decimals=..., tol=..., output_names=..., treatment_names=...) -> None:
        ...
    
    def __str__(self) -> str:
        ...
    
    @property
    def mean_point(self): # -> Incomplete:
        """
        Get the mean of the point estimate of each treatment on each outcome for sample X.

        Returns
        -------
        mean_point : array_like, shape (d_y, d_t)
            The point estimate of each treatment on each outcome for sample X.
            Note that when Y or T is a vector rather than a 2-dimensional array,
            the corresponding singleton dimensions in the output will be collapsed
            (e.g. if both are vectors, then the output of this method will be a scalar)
        """
        ...
    
    @property
    def stderr_mean(self): # -> Any:
        """
        Get the standard error of the mean point estimate of each treatment on each outcome for sample X.

        The output is a conservative upper bound.

        Returns
        -------
        stderr_mean : array_like, shape (d_y, d_t)
            The standard error of the mean point estimate of each treatment on each outcome for sample X.
            Note that when Y or T is a vector rather than a 2-dimensional array,
            the corresponding singleton dimensions in the output will be collapsed
            (e.g. if both are vectors, then the output of this method will be a scalar)
        """
        ...
    
    def zstat(self, *, value=...): # -> Any:
        """
        Get the z statistic of the mean point estimate of each treatment on each outcome for sample X.

        Parameters
        ----------
        value:  float, optional
            The mean value of the metric you'd like to test under null hypothesis.

        Returns
        -------
        zstat : array_like, shape (d_y, d_t)
            The z statistic of the mean point estimate of each treatment on each outcome for sample X.
            Note that when Y or T is a vector rather than a 2-dimensional array,
            the corresponding singleton dimensions in the output will be collapsed
            (e.g. if both are vectors, then the output of this method will be a scalar)
        """
        ...
    
    def pvalue(self, *, value=...): # -> ndarray[_AnyShape, dtype[Any]] | ndarray[tuple[()], dtype[Any]]:
        """
        Get the p value of the z test of each treatment on each outcome for sample X.

        Parameters
        ----------
        value:  float, optional
            The mean value of the metric you'd like to test under null hypothesis.

        Returns
        -------
        pvalue : array_like, shape (d_y, d_t)
            The p value of the z test of each treatment on each outcome for sample X.
            Note that when Y or T is a vector rather than a 2-dimensional array,
            the corresponding singleton dimensions in the output will be collapsed
            (e.g. if both are vectors, then the output of this method will be a scalar)
        """
        ...
    
    def conf_int_mean(self, *, alpha=...): # -> tuple[Incomplete, Incomplete]:
        """
        Get the confidence interval of the mean point estimate of each treatment on each outcome for sample X.

        Parameters
        ----------
        alpha:  float in [0, 1], optional
            The overall level of confidence of the reported interval.
            The alpha/2, 1-alpha/2 confidence interval is reported.

        Returns
        -------
        lower, upper: tuple of array, shape (d_y, d_t)
            The lower and the upper bounds of the confidence interval for each quantity.
            Note that when Y or T is a vector rather than a 2-dimensional array,
            the corresponding singleton dimensions in the output will be collapsed
            (e.g. if both are vectors, then the output of this method will also be a vector)
        """
        ...
    
    @property
    def std_point(self): # -> Any:
        """
        Get the standard deviation of the point estimate of each treatment on each outcome for sample X.

        Returns
        -------
        std_point : array_like, shape (d_y, d_t)
            The standard deviation of the point estimate of each treatment on each outcome for sample X.
            Note that when Y or T is a vector rather than a 2-dimensional array,
            the corresponding singleton dimensions in the output will be collapsed
            (e.g. if both are vectors, then the output of this method will be a scalar)
        """
        ...
    
    def percentile_point(self, *, alpha=...): # -> tuple[Any, Any]:
        """
        Get the confidence interval of the point estimate of each treatment on each outcome for sample X.

        Parameters
        ----------
        alpha:  float in [0, 1], default 0.05
            The overall level of confidence of the reported interval.
            The alpha/2, 1-alpha/2 confidence interval is reported.

        Returns
        -------
        lower, upper: tuple of array, shape (d_y, d_t)
            The lower and the upper bounds of the confidence interval for each quantity.
            Note that when Y or T is a vector rather than a 2-dimensional array,
            the corresponding singleton dimensions in the output will be collapsed
            (e.g. if both are vectors, then the output of this method will also be a vector)
        """
        ...
    
    def conf_int_point(self, *, alpha=..., tol=...): # -> tuple[NDArray[Any], NDArray[Any]]:
        """
        Get the confidence interval of the point estimate of each treatment on each outcome for sample X.

        Parameters
        ----------
        alpha:  float in [0, 1], optional
            The overall level of confidence of the reported interval.
            The alpha/2, 1-alpha/2 confidence interval is reported.
        tol:  optinal float
            The stopping criterion. The iterations will stop when the outcome is less than ``tol``

        Returns
        -------
        lower, upper: tuple of array, shape (d_y, d_t)
            The lower and the upper bounds of the confidence interval for each quantity.
            Note that when Y or T is a vector rather than a 2-dimensional array,
            the corresponding singleton dimensions in the output will be collapsed
            (e.g. if both are vectors, then the output of this method will also be a vector)
        """
        ...
    
    @property
    def stderr_point(self): # -> Any:
        """
        Get the standard error of the point estimate of each treatment on each outcome for sample X.

        Returns
        -------
        stderr_point : array_like, shape (d_y, d_t)
            The standard error of the point estimate of each treatment on each outcome for sample X.
            Note that when Y or T is a vector rather than a 2-dimensional array,
            the corresponding singleton dimensions in the output will be collapsed
            (e.g. if both are vectors, then the output of this method will be a scalar)
        """
        ...
    
    def summary(self, alpha=..., value=..., decimals=..., tol=..., output_names=..., treatment_names=...): # -> Summary:
        """
        Get a summary of this instance's information.

        Parameters
        ----------
        alpha:  float in [0, 1], optional
            The overall level of confidence of the reported interval.
            The alpha/2, 1-alpha/2 confidence interval is reported.
        value:  float, optional
            The mean value of the metric you'd like to test under null hypothesis.
        decimals:  int, optional
            Number of decimal places to round each column to.
        tol:  float, optional
            The stopping criterion. The iterations will stop when the outcome is less than ``tol``
        output_names: list of str, optional
                The names of the outputs
        treatment_names: list of str, optional
            The names of the treatments

        Returns
        -------
        smry : Summary instance
            this holds the summary tables and text, which can be printed or
            converted to various output formats.
        """
        ...
    


